commercetools/commercetools-jvm-sdk

- models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
@schleichardt I solved it filtering by ID. The filter was done after receiving the results nonetheless, so I guessed why not better do it before?
> Fix search IT with filter by ID.

- common/src/main/java/io/sphere/sdk/models/Base.java
- common/src/main/java/io/sphere/sdk/models/SdkDefaults.java
- models/src/main/java/io/sphere/sdk/categories/Category.java
- models/src/main/java/io/sphere/sdk/customers/CustomerDraft.java
- models/src/main/java/io/sphere/sdk/customers/CustomerDraftBuilder.java
- models/src/main/java/io/sphere/sdk/customers/CustomerImpl.java
> TO_STRING_STYLE should not be in Base

- common/src/main/java/io/sphere/sdk/http/UrlUtils.java
- common/src/main/java/io/sphere/sdk/models/LocalizedStrings.java
- common/src/main/java/io/sphere/sdk/search/SearchDslImpl.java
- common/src/test/java/io/sphere/sdk/models/LocalizedStringsTest.java
- models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
- models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
> Fix URL encoding

- models/src/main/java/io/sphere/sdk/states/StateBuilder.java
- models/src/main/java/io/sphere/sdk/states/commands/StateUpdateCommand.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/ChangeInitial.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/ChangeKey.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/ChangeType.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/SetDescription.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/SetName.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/SetTransitions.java
- models/src/main/java/io/sphere/sdk/states/commands/updateactions/package-info.java
Please have a look at the StateBuilder which might be useful for Unit-Tests and the missing UpdateActions<State>. Not sure if SetTransitions is correct according the Array and List<State>.
> Implementation of StateBuilder for Unit-Tests and UpdateActions for State

- common/src/main/java/io/sphere/sdk/queries/EmbeddedPredicate.java
- common/src/main/java/io/sphere/sdk/queries/PredicateBase.java
- common/src/test/java/io/sphere/sdk/queries/PredicateBaseTest.java
- models/src/main/java/io/sphere/sdk/products/queries/ProductAllVariantsQueryModel.java
- models/src/main/java/io/sphere/sdk/products/queries/ProductDataQueryModel.java
- models/src/main/java/io/sphere/sdk/products/queries/ProductDataQueryModelBase.java
- models/src/main/java/io/sphere/sdk/products/queries/ProductVariantQueryModel.java
- models/src/test/java/io/sphere/sdk/products/ProductQueryCombinationTest.java
- models/src/test/java/io/sphere/sdk/products/queries/ProductDataQueryModelBaseTest.java
- models/src/test/java/io/sphere/sdk/products/queries/ProductVariantQueryModelTest.java
> Query improvements

- common/src/main/java/io/sphere/sdk/client/JsonNodeSphereRequest.java
- common/src/main/java/io/sphere/sdk/client/SphereRequest.java
- common/src/main/java/io/sphere/sdk/client/SphereRequestDecorator.java
- common/src/main/java/io/sphere/sdk/commands/CommandImpl.java
- common/src/main/java/io/sphere/sdk/queries/Fetch.java
- common/src/main/java/io/sphere/sdk/queries/FetchImpl.java
- common/src/main/java/io/sphere/sdk/queries/Query.java
- common/src/main/java/io/sphere/sdk/queries/QueryDslBuilder.java
- common/src/main/java/io/sphere/sdk/queries/QueryDslImpl.java
- common/src/main/java/io/sphere/sdk/queries/QueryToFetchAdapter.java
- common/src/main/java/io/sphere/sdk/search/Search.java
- common/src/main/java/io/sphere/sdk/search/SearchDslBuilder.java
- common/src/main/java/io/sphere/sdk/search/SearchDslImpl.java
- java-client-core/src/main/java/io/sphere/sdk/client/DeprecationExceptionSphereClientDecorator.java
- java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- java-client-core/src/test/java/io/sphere/sdk/client/DummySphereRequest.java
- models/src/it/java/io/sphere/sdk/categories/CategoryByNameQuery.java
- models/src/it/java/io/sphere/sdk/customobjects/demo/GsonFooCustomObjectUpsertCommand.java
- models/src/it/java/io/sphere/sdk/errors/SphereExceptionTest.java
- models/src/main/java/io/sphere/sdk/customers/commands/CustomerSignInCommand.java
- models/src/main/java/io/sphere/sdk/customobjects/commands/CustomObjectCustomJsonMappingUpsertCommand.java
- models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectCustomJsonMappingByKeyFetch.java
- models/src/main/java/io/sphere/sdk/projects/queries/ProjectGet.java
- models/src/main/java/io/sphere/sdk/shippingmethods/queries/GetShippingMethodsByCart.java
- models/src/main/java/io/sphere/sdk/shippingmethods/queries/GetShippingMethodsByLocation.java
> Refactor sphere request 355

- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ExperimentalProductProjectionSearchModel.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductDataSearchModelBase.java
- sphere-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
- sphere-models/src/test/java/io/sphere/sdk/products/search/VariantSearchSortTest.java
@schleichardt please review (missing release notes).
Fixes #350
> Rename method variants to allVariants

- sphere-common/src/main/java/io/sphere/sdk/queries/EntityQuery.java
- sphere-common/src/main/java/io/sphere/sdk/queries/IntegerLikeQuerySortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/queries/IntegerQuerySortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/queries/LongQuerySortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QueryDsl.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QueryDslBuilder.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QueryDslImpl.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QuerySort.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QuerySortBase.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QuerySortDirection.java
- sphere-common/src/main/java/io/sphere/sdk/queries/QuerySortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/queries/SimpleQuerySort.java
- sphere-common/src/main/java/io/sphere/sdk/queries/SortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/queries/SphereQuerySort.java
- sphere-common/src/main/java/io/sphere/sdk/queries/StringQuerySortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/queries/TimestampSortingModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/SearchSortingModel.java
- sphere-common/src/test/java/io/sphere/sdk/queries/QueryDslTest.java
- sphere-common/src/test/java/io/sphere/sdk/queries/SphereSortTest.java
- sphere-common/src/test/java/io/sphere/sdk/queries/StringQuerySortingModelTest.java
- sphere-models/src/it/java/io/sphere/sdk/categories/CategoryIntegrationTest.java
- sphere-models/src/it/java/io/sphere/sdk/customers/queries/CustomerQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/customobjects/queries/CustomObjectQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/inventories/queries/InventoryEntryQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/orders/queries/OrderQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodQueryModelTest.java
- src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- src/test/java/io/sphere/sdk/meta/QueryDocumentationTest.java
- src/test/java/io/sphere/sdk/queries/QueryDemo.java
@schleichardt please review.
Fixes https://github.com/sphereio/sphere-jvm-sdk/issues/267
> Rename query sort

- sphere-common/src/main/java/io/sphere/sdk/search/BooleanSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/CurrencySearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/DateSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/DateTimeSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/FilterSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/MoneyAmountSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/NumberSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/RangeTermModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/RangedFacetSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/RangedFilterSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/ReferenceSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/StringSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/TermModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/TimeSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/TypeSerializer.java
- sphere-common/src/test/java/io/sphere/sdk/search/TypeSerializerTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
- sphere-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
Some improvements like better naming, better tests to be included in the documentation and correct date time implementation.
@schleichardt please review.
> Improve search API

- build.sbt
- project/Build.scala
- sphere-java-client-core/src/main/java/io/sphere/sdk/client/TimeoutSphereClientDecorator.java
- sphere-java-client-core/src/test/java/io/sphere/sdk/client/TimeoutSphereClientDecoratorTest.java
Add assertj library for assertions in tests. #387 
> Add client decorator for timeouts. close #345

- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
It is probably go on failing, but it has already passed many times in the branch. Let's try in the PR and then in master. At least I think these values are good.
> Adjust retry

- sphere-common/src/main/java/io/sphere/sdk/client/ClientPackage.java
- sphere-common/src/main/java/io/sphere/sdk/client/SphereApiConfigImpl.java
- sphere-common/src/main/java/io/sphere/sdk/client/SphereAuthConfigImpl.java
- sphere-common/src/main/java/io/sphere/sdk/client/SphereClientConfig.java
- sphere-common/src/test/java/io/sphere/sdk/client/SphereApiConfigTest.java
- sphere-common/src/test/java/io/sphere/sdk/client/SphereAuthConfigTest.java
- sphere-common/src/test/java/io/sphere/sdk/client/SphereClientConfigTest.java
> Do null checks for configuration values. close #369

- project/DocumentationTaglet.java
- sphere-models/src/it/java/io/sphere/sdk/reviews/ReviewFixtures.java
- sphere-models/src/it/java/io/sphere/sdk/reviews/commands/ReviewCreateCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/reviews/commands/ReviewUpdateCommandTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductIdentifiable.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductLike.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/Review.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/ReviewDraft.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/ReviewDraftBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/ReviewImpl.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/ReviewCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/ReviewUpdateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/ReviewsEndpoint.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/updateactions/SetAuthorName.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/updateactions/SetScore.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/updateactions/SetText.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/updateactions/SetTitle.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/queries/ReviewQuery.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/queries/ReviewQueryModel.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/queries/ReviewsEndpoint.java
- sphere-models/src/test/java/io/sphere/sdk/reviews/ReviewDraftTest.java
- sphere-models/src/test/java/io/sphere/sdk/reviews/commands/updateactions/SetScoreTest.java
@lauraluiz please review, but don't merge, since I want to discuss sth. after your review which may requires additional changes.
> Implement the reviews endpoints and models. close #359

- sphere-models/src/it/java/io/sphere/sdk/projects/queries/ProjectGetTest.java
- sphere-models/src/main/java/io/sphere/sdk/projects/Project.java
- sphere-models/src/main/java/io/sphere/sdk/projects/TrialUntilDeserializer.java
> Project endpoint 364

- sphere-models/src/main/java/io/sphere/sdk/products/search/ExperimentalProductProjectionSearchModel.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductDataSearchModelBase.java
- sphere-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
> Add product type in search endpoint for products

- sphere-models/src/it/java/io/sphere/sdk/carts/commands/CartUpdateCommandTest.java
- sphere-models/src/main/java/io/sphere/sdk/carts/LineItem.java
- sphere-models/src/main/java/io/sphere/sdk/carts/LineItemBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/carts/LineItemImpl.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddLineItem.java
- sphere-models/src/main/java/io/sphere/sdk/channels/ChannelRoles.java
Add distributionChannel field to LineItem and AddLineItem. close #503
> Add ChannelRole ProductDistribution. close #502

- sphere-common/src/main/java/io/sphere/sdk/commands/UpdateCommand.java
- sphere-models/src/it/java/io/sphere/sdk/categories/commands/CategoryUpdateCommandTest.java
> Add getter for update actions into UpdateCommand interface. close #652

- sphere-common/src/main/java/io/sphere/sdk/models/Address.java
- sphere-common/src/test/java/io/sphere/sdk/models/AddressTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/Price.java
- sphere-models/src/main/java/io/sphere/sdk/taxcategories/TaxRate.java
- sphere-models/src/main/java/io/sphere/sdk/taxcategories/TaxRateBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/taxcategories/TaxRateImpl.java
- sphere-models/src/test/java/io/sphere/sdk/products/PriceTest.java
- sphere-models/src/test/java/io/sphere/sdk/taxcategories/TaxRateTest.java
> Add methods to compare Address|TaxRate|Price without ids. close #91

- sphere-common/src/main/java/io/sphere/sdk/search/BooleanSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/CurrencySearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/DateSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/DateTimeSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/MoneyCentAmountSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/NumberSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/RangeTermModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/RangeTermModelImpl.java
- sphere-common/src/main/java/io/sphere/sdk/search/SearchModelImpl.java
- sphere-common/src/main/java/io/sphere/sdk/search/StringSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/TermModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/TermModelImpl.java
- sphere-common/src/main/java/io/sphere/sdk/search/TimeSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/UntypedSearchModel.java
- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchFilterTypesIntegrationTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
- sphere-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
- sphere-test-lib/src/main/java/io/sphere/sdk/test/RetryIntegrationTest.java
@schleichardt please review. I've created an UntypedSearchModel that accepts simple Strings, therefore removing all type-safety that can be annoying when dealing with input from e.g. query strings.
> Untyped search model

- sphere-common/src/main/java/io/sphere/sdk/json/TypeReferences.java
- sphere-models/src/it/java/io/sphere/sdk/producttypes/ProductTypeAttributesTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/attributes/AttributeAccess.java
> Add AttributeAccess for Integer and Long values. close #685

- sphere-common/src/main/java/io/sphere/sdk/search/SearchKeywords.java
- sphere-models/src/it/java/io/sphere/sdk/products/ProductFixtures.java
- sphere-models/src/it/java/io/sphere/sdk/products/queries/SuggestQueryTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/Suggestion.java
- sphere-models/src/main/java/io/sphere/sdk/products/SuggestionImpl.java
- sphere-models/src/main/java/io/sphere/sdk/products/SuggestionResult.java
- sphere-models/src/main/java/io/sphere/sdk/products/SuggestionResultImpl.java
- sphere-models/src/main/java/io/sphere/sdk/products/queries/SuggestQuery.java
- sphere-models/src/main/java/io/sphere/sdk/products/queries/SuggestQueryImpl.java
- sphere-models/src/test/java/io/sphere/sdk/products/SuggestionResultTest.java
> Add query suggestion endpoint. close #683

- sphere-common/src/main/java/io/sphere/sdk/commands/MetaModelByIdDeleteCommandBuilder.java
- sphere-common/src/main/java/io/sphere/sdk/commands/MetaModelByIdDeleteCommandImpl.java
- sphere-common/src/main/java/io/sphere/sdk/commands/MetaModelUpdateCommandDslBuilder.java
- sphere-common/src/main/java/io/sphere/sdk/commands/MetaModelUpdateCommandDslImpl.java
- sphere-common/src/main/java/io/sphere/sdk/commands/UpdateCommandDsl.java
- sphere-common/src/main/java/io/sphere/sdk/commands/UpdateCommandDslBuilder.java
- sphere-common/src/main/java/io/sphere/sdk/commands/UpdateCommandDslImpl.java
- sphere-common/src/main/java/io/sphere/sdk/models/Resource.java
- sphere-common/src/main/java/io/sphere/sdk/models/ResourceImpl.java
- sphere-common/src/main/java/io/sphere/sdk/models/ResourceView.java
- sphere-common/src/main/java/io/sphere/sdk/models/ResourceViewImpl.java
- sphere-models/src/it/java/io/sphere/sdk/products/commands/ProductUpdateCommandTest.java
- sphere-models/src/main/java/io/sphere/sdk/customobjects/CustomObject.java
- sphere-models/src/main/java/io/sphere/sdk/customobjects/CustomObjectImpl.java
- sphere-models/src/main/java/io/sphere/sdk/products/Product.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductIdentifiable.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductLike.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductProjection.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductProjectionImpl.java
- sphere-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionByIdGet.java
- sphere-models/src/test/java/io/sphere/sdk/products/ProductProjectionTest.java
I am not even sure if we should do it.
But is has some charm to use `ProductProjection` as parameter for `Product` commands.
> ProductProjection is a Versioned<Product>. close #677

- sphere-models/src/it/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountCreateCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/queries/ProductQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/queries/SuggestQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/projects/queries/ProjectGetTest.java
- sphere-test-lib/src/main/java/io/sphere/sdk/test/SphereTestUtils.java
> handle eventual consistency

- sphere-models/src/it/java/io/sphere/sdk/productdiscounts/ProductDiscountFixtures.java
@schleichardt the test `io.sphere.sdk.products.queries.ProductQueryTest.queryProductsWithAnyDiscount` cannot success with an inactive discount
> activate discount

- sphere-common/src/main/java/io/sphere/sdk/search/MetaModelSearchDslImpl.java
- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchFilterTypesIntegrationTest.java
> Fix platform deprecation warning boolean facet formatting. close #704

- sphere-common/src/main/java/io/sphere/sdk/search/EntitySearch.java
- sphere-common/src/main/java/io/sphere/sdk/search/MetaModelSearchDsl.java
- sphere-common/src/main/java/io/sphere/sdk/search/MetaModelSearchDslBuilder.java
- sphere-common/src/main/java/io/sphere/sdk/search/MetaModelSearchDslImpl.java
- sphere-common/src/main/java/io/sphere/sdk/search/PagedSearchResult.java
- sphere-common/src/main/java/io/sphere/sdk/search/SearchDsl.java
- sphere-common/src/main/java/io/sphere/sdk/search/SearchParameterKeys.java
- sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearch.java
> Add fuzzy search. close #735

- sphere-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientFactory.java
- sphere-java-client/src/it/java/example/JavaClientInstantiationExample.java
- sphere-models/src/it/java/io/sphere/sdk/client/SphereClientFactoryTest.java
@lauraluiz @yanns please review
> Enable implicit http client configuration. closes #722, closes #699

- sphere-models/src/it/java/io/sphere/sdk/customergroups/commands/CustomerGroupCreateCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/customergroups/commands/CustomerGroupDeleteCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/customergroups/queries/CustomerGroupByIdGetTest.java
- sphere-models/src/it/java/io/sphere/sdk/customergroups/queries/CustomerGroupQueryTest.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/CustomerGroup.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/CustomerGroupDraft.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/commands/CustomerGroupCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/commands/CustomerGroupDeleteCommand.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/commands/CustomerGroupUpdateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/commands/updateactions/ChangeName.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/queries/CustomerGroupByIdGet.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/queries/CustomerGroupQuery.java
> Review customer groups package. close #758

- sphere-models/src/it/java/io/sphere/sdk/categories/commands/CategoryUpdateCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/categories/queries/CategoryByIdGetTest.java
- sphere-models/src/it/java/io/sphere/sdk/categories/queries/CategoryQueryTest.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomLineItemCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomLineItemCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetLineItemCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetLineItemCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/categories/Category.java
- sphere-models/src/main/java/io/sphere/sdk/categories/CategoryDraftBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/categories/CategoryTree.java
- sphere-models/src/main/java/io/sphere/sdk/categories/commands/CategoryUpdateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/ChangeName.java
- sphere-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/ChangeParent.java
- sphere-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/categories/queries/CategoryByIdGet.java
- sphere-models/src/main/java/io/sphere/sdk/categories/queries/CategoryQuery.java
- sphere-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetCustomLineItemCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetCustomLineItemCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetCustomType.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetLineItemCustomField.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetLineItemCustomType.java
- sphere-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
> Review category package. close #752

- sphere-models/src/it/java/io/sphere/sdk/carts/commands/CartCreateCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/carts/commands/CartUpdateCommandTest.java
- sphere-models/src/it/java/io/sphere/sdk/carts/queries/CartQueryTest.java
- sphere-models/src/main/java/io/sphere/sdk/carts/Cart.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CartDraftBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CartLike.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CartShippingInfo.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CustomLineItem.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CustomLineItemDraft.java
- sphere-models/src/main/java/io/sphere/sdk/carts/LineItem.java
- sphere-models/src/main/java/io/sphere/sdk/carts/LineItemLike.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/CartUpdateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddCustomLineItem.java
- sphere-models/src/main/java/io/sphere/sdk/carts/expansion/CartExpansionModel.java
- sphere-models/src/main/java/io/sphere/sdk/carts/expansion/CartLikeExpansionModel.java
- sphere-models/src/main/java/io/sphere/sdk/carts/queries/CartByCustomerIdGet.java
- sphere-models/src/main/java/io/sphere/sdk/carts/queries/CartLikeQueryModel.java
- sphere-models/src/main/java/io/sphere/sdk/carts/queries/CartQuery.java
- sphere-models/src/main/java/io/sphere/sdk/carts/queries/CartQueryModel.java
- sphere-models/src/main/java/io/sphere/sdk/carts/queries/LineItemCollectionQueryModel.java
- sphere-models/src/main/java/io/sphere/sdk/orders/queries/OrderQueryModel.java
> Review cart package. close #750

- sphere-models/src/it/java/io/sphere/sdk/channels/queries/ChannelByIdGetTest.java
- sphere-models/src/it/java/io/sphere/sdk/channels/queries/ChannelQueryTest.java
- sphere-models/src/main/java/io/sphere/sdk/channels/ChannelDraft.java
- sphere-models/src/main/java/io/sphere/sdk/channels/ChannelDraftBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/channels/ChannelRole.java
- sphere-models/src/main/java/io/sphere/sdk/channels/commands/ChannelCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/channels/commands/ChannelUpdateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/channels/queries/ChannelByIdGet.java
- sphere-models/src/main/java/io/sphere/sdk/channels/queries/ChannelQuery.java
- sphere-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
> Review channel package. close #754

- sphere-common/src/main/java/io/sphere/sdk/json/MoneyDeserializer.java
- sphere-common/src/main/java/io/sphere/sdk/json/MoneyRepresentation.java
- sphere-common/src/main/java/io/sphere/sdk/json/MoneySerializer.java
- sphere-common/src/main/java/io/sphere/sdk/utils/MoneyImpl.java
- sphere-models/src/it/java/io/sphere/sdk/products/commands/ProductUpdateCommandTest.java
- sphere-models/src/test/java/io/sphere/sdk/products/MoneyTest.java
- src/main/java/io/sphere/sdk/meta/FormattingDocumentation.java
- src/test/java/io/sphere/sdk/meta/FormattingDocumentationTest.java
@cneijenhuis I also would like to get your feedback for this pull request.
> improve cent amount calculation, close #789

- sphere-models/src/it/java/io/sphere/sdk/products/ProductCategoryOrderHintTest.java
> use assert eventually on search

- sphere-common/src/main/java/io/sphere/sdk/search/model/FacetAndFilterSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/model/FacetSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/model/FilterSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/model/TermFacetAndFilterBaseSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/model/TermFacetBaseSearchModel.java
- sphere-common/src/main/java/io/sphere/sdk/search/model/TermFilterBaseSearchModel.java
My last step towards completition :)
Now all models have a common interface that covers the minimum functionality.
Please @schleichardt review.
> Add filter/facet interfaces as in sort

- sphere-models/src/it/java/io/sphere/sdk/products/search/ProductProjectionSearchMainIntegrationTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductProjection.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductVariant.java
- sphere-models/src/main/java/io/sphere/sdk/products/ProductVariantImpl.java
- sphere-models/src/test/java/io/sphere/sdk/products/ProductProjectionTest.java
- sphere-models/src/test/resources/ProductProjectionTest/product-projection-from-query.json
- sphere-models/src/test/resources/ProductProjectionTest/product-projection-from-search.json
@schleichardt please review.
@agourlay also review. Check that I created some IT that currently are disabled because the flag is not working as it would be desirable. We can use them as a guide of what's left to do :)
> Is matching variant flag, closes #830

- sphere-models/src/it/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetedSearchIntegrationTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetsIntegrationTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFiltersIntegrationTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/search/ProductProjectionSearchModelSortIntegrationTest.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductAttributeFacetAndFilterSearchModel.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductAttributeFacetSearchModel.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductAttributeFilterSearchModel.java
- sphere-models/src/main/java/io/sphere/sdk/products/search/ProductAttributeSortSearchModel.java
- sphere-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
> Fix typo for localizedEnum in Search DSL, closes #883

- sdk-http-apache-async/src/main/java/io/sphere/sdk/http/ApacheHttpClientAdapterImpl.java
- sdk-http/src/main/java/io/sphere/sdk/http/HttpHeaders.java
- sphere-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
> Request gzipped responses from sphere. close #873

- sphere-models/src/it/java/io/sphere/sdk/carts/commands/CartCreateCommandTest.java
- sphere-models/src/main/java/io/sphere/sdk/carts/CartLike.java
> Add getCurrency() to cart and order. close #870

- sphere-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientFactory.java
- sphere-models/src/it/java/io/sphere/sdk/client/SphereClientFactoryTest.java
- sphere-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
> Ease to initialise a client with an access token. close #749

- sphere-common/src/main/java/io/sphere/sdk/search/SearchDsl.java
- sphere-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
- src/main/java/io/sphere/sdk/meta/TroubleshootingGuide.java
> Document failing search for unactivated language. close #667

- sphere-java-client-core/src/main/java/io/sphere/sdk/client/BlockingSphereClient.java
- sphere-java-client-core/src/main/java/io/sphere/sdk/client/TimeoutSphereClientDecorator.java
- sphere-java-client-core/src/test/java/io/sphere/sdk/client/BlockingSphereClientTest.java
- sphere-java-client-core/src/test/java/io/sphere/sdk/client/TimeoutSphereClientDecoratorTest.java
- sphere-java-client-core/src/test/java/io/sphere/sdk/client/WrongBlockingWithGetAndSignature.java
- sphere-java-client-core/src/test/java/io/sphere/sdk/client/WrongBlockingWithGetAndSwallowing.java
- sphere-java-client-core/src/test/java/io/sphere/sdk/client/WrongBlockingWithJoin.java
- src/main/java/io/sphere/sdk/meta/GettingStarted.java
- src/main/java/io/sphere/sdk/meta/SphereClientTuningDocumentation.java
- src/test/java/io/sphere/sdk/client/BlockingClientCreationDemo.java
- src/test/java/io/sphere/sdk/client/BlockingClientSphereExceptionDemo.java
- src/test/java/io/sphere/sdk/meta/BlockingClientValueAsyncGetDemo.java
- src/test/java/io/sphere/sdk/meta/BlockingClientValueGetDemo.java
- src/test/java/io/sphere/sdk/meta/SphereClientTuningDocumentationTest.java
@lauraluiz please review.
I hope the doc preview will appear at http://sphereio.github.io/sphere-jvm-sdk/javadoc/feature/907/client-docu/index.html
> Improve client docu. close #907

- sphere-models/src/it/java/io/sphere/sdk/projects/queries/ProjectGetTest.java
- sphere-models/src/main/java/io/sphere/sdk/projects/Project.java
> Add currencies to project endpoint. close #928

- sphere-models/src/it/java/io/sphere/sdk/products/queries/ProductProjectionQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/products/queries/ProductQueryTest.java
- sphere-models/src/it/java/io/sphere/sdk/reviews/commands/ReviewCreateCommandTest.java
> the review statistics are applied asynchronously

- sphere-common/src/main/java/io/sphere/sdk/client/SphereRequestDecorator.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/MetricObservable.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/MetricSphereRequest.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedDeserializationDuration.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedDuration.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedDurationBase.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedSerializationDuration.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedTotalDuration.java
- sphere-convenience/src/main/java/io/sphere/sdk/client/metrics/SimpleMetricsSphereClient.java
- sphere-convenience/src/test/java/io/sphere/sdk/client/metrics/Logger.java
- sphere-convenience/src/test/java/io/sphere/sdk/client/metrics/SimpleMetricsSphereClientDemo.java
- sphere-convenience/src/test/java/io/sphere/sdk/client/metrics/SimpleMetricsSphereClientTest.java
@yanns @lauraluiz please review
When the travis build completes on  http://sphereio.github.io/sphere-jvm-sdk/javadoc/simple-metric/io/sphere/sdk/client/metrics/package-frame.html should appear some Javadoc as HTML.
> Add a simple metrics sphere client decorator.

- sphere-common/src/main/java/io/sphere/sdk/commands/CreateCommandImpl.java
- sphere-common/src/main/java/io/sphere/sdk/commands/DraftBasedCreateCommand.java
- sphere-common/src/main/java/io/sphere/sdk/commands/MetaModelCreateCommandImpl.java
- sphere-models/src/it/java/io/sphere/sdk/categories/commands/CategoryCreateCommandIntegrationTest.java
- sphere-models/src/main/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/carts/commands/CartCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/categories/CategoryDraftBuilder.java
- sphere-models/src/main/java/io/sphere/sdk/categories/commands/CategoryCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/channels/commands/ChannelCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/customergroups/commands/CustomerGroupCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/customers/commands/CustomerCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/customobjects/commands/CustomObjectUpsertCommand.java
- sphere-models/src/main/java/io/sphere/sdk/discountcodes/commands/DiscountCodeCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/inventory/commands/InventoryEntryCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/orders/commands/OrderFromCartCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/payments/commands/PaymentCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/products/commands/ProductCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/producttypes/commands/ProductTypeCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/reviews/commands/ReviewCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/shippingmethods/commands/ShippingMethodCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/states/commands/StateCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/taxcategories/commands/TaxCategoryCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/types/commands/TypeCreateCommand.java
- sphere-models/src/main/java/io/sphere/sdk/zones/commands/ZoneCreateCommand.java
- sphere-models/src/test/java/io/sphere/sdk/categories/commands/CategoryCreateCommandTest.java
> Add getter for drafts on create commands. close #951

- src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
@schleichardt review and merge if it's good.
> Update ReleaseNotes with Search endpoint changes

- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariant.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelection.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelectionBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelectionDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearch.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearchImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/PriceSelectionIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/ProductTypeFixtures.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/SphereJsonUtils.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/MetaModelSearchDslImpl.java
- commercetools-test-lib/src/main/java/io/sphere/sdk/test/SphereTestUtils.java
- pom.xml
> support for new price filtering options, close #828

- .travis.yml
- commercetools-internal-docs/pom.xml
- commercetools-internal-docs/src/test/java/introspection/IntrospectionUtils.java
- commercetools-internal-docs/src/test/java/introspection/rules/ResourceDraftBuildersCanBeCreatedByDrafts.java
- commercetools-internal-docs/src/test/java/introspection/rules/RulesMain.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/PaymentDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/TransactionDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/reviews/ReviewDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/types/CustomFieldsDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/types/TypeDraftBuilder.java
- pom.xml
> builders from drafts, close #1000

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/ExceptionFactory.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/ConcurrentModificationException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/MetaModelUpdateCommandDslImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/UpdateCommandDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/errors/ConcurrentModification.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/errors/ConcurrentModificationError.java
> add field currentVersion for version conflict error, close #1002

- .travis.yml
@lauraluiz I want to try out in travis to only build the master branches and pull requests. The thing is, a lot of small commits in a branch which is not ready yet keep the important builds waiting.
> build only master branch and pull requests in travis

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/CustomObjectDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectQueryModel.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectQueryModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectValueRootJsonObjectQueryModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectValueRootJsonQueryModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/queries/CustomObjectQueryIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/queries/CustomObjectQueryModelTest.java
- commercetools-models/src/test/java/io/sphere/sdk/messages/queries/MessageByIdGetIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/IntegerQueryModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/JsonObjectQueryModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/JsonQueryModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/JsonValueQueryModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/QueryModelImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/RootJsonQueryModel.java
currently the API does not support values in the query. so later I need to retrigger the tests
> query by custom object value, close #999, close #1010

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereDeprecationException.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/ServerErrorExceptionDemoTest.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/BadGatewayException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/BadRequestException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/ErrorResponseException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/GatewayTimeoutException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/InternalServerErrorException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/InvalidClientCredentialsException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/InvalidTokenException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/NotFoundException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/ServerErrorException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/ServiceUnavailableException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereServiceException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereTimeoutException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/UnauthorizedException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/SphereException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/InvalidRangeException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/InvertedBoundsException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SameExclusiveBoundsException.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/search/model/RangeTest.java
- sdk-http/src/main/java/io/sphere/sdk/http/HttpException.java
> exception docu, close #963

- commercetools-java-client-ahc-2_0/src/main/java/io/sphere/sdk/client/SphereAsyncHttpClientFactory.java
> set http client default timeout (request, read) to 121s, close #1039

- commercetools-models/src/main/java/io/sphere/sdk/payments/commands/updateactions/ChangeAmountPlanned.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentUpdateCommandIntegrationTest.java
> add ChangeAmountPlanned update action, close #1028

- commercetools-models/src/main/java/io/sphere/sdk/types/commands/TypeDeleteCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/types/commands/TypeUpdateCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/types/commands/TypeDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/types/commands/TypeUpdateCommandIntegrationTest.java
> update or delete type by key, close #1034

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/BlockingSphereClientImpl.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/BlockingSphereClientTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientUtils.java
> add SphereRequest to stacktrace on timeouts with BlockingSphereClient, close #1038

- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetPrices.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> Added new update action SetPrices

- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/LegacySetSku.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetSku.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> add the stageable SKU update action, close #1078

- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerCreateEmailTokenCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerPasswordResetCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerVerifyEmailCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerCreateEmailTokenCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerPasswordResetCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerPasswordResetCommandUnitTest.java
> customer is not needed anymore as parameters for password reset and password confirmation, close #1081

- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchFacetedSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchFacetsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchFiltersIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchMainIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchSortIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/ExistsAndMissingFilterSearchModelSupportUtils.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/FacetSearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/FacetedSearchSearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/FilterSearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SearchModelExpression.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SortExpressionImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SortSearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SortSearchModelImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFacetBaseSearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFacetedSearchBaseSearchModel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFilterBaseSearchModel.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/search/model/SearchModelTest.java
> Enable access to search model and attribute path

- README.md
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/ExceptionFactory.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/ProjectScopes.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensFacade.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplier.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/client/TokensFacadeIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/ClientPackage.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/ForbiddenException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereAuthConfig.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereAuthConfigBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereAuthConfigImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfig.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfigBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfigUtils.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereProjectScope.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereScope.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/SphereException.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereAuthConfigBuilderTest.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereClientConfigBuilderTest.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereClientConfigTest.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereProjectScopeTest.java
> support auth scopes, close #1045

- .travis.yml
- commercetools-models/src/main/java/io/sphere/sdk/inventory/AvailabilityInfo.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/AvailabilityInfoBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/AvailabilityInfoImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariant.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantAvailability.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantAvailabilityImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelProductVariantAvailabilityFilterSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelProductVariantAvailabilitySortSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelsProductVariantAvailabilityFilterSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelsProductVariantAvailabilityFilterSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelsProductVariantAvailabilitySortSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelsProductVariantAvailabilitySortSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilityFilterSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilityFilterSearchModelCommon.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilityFilterSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilitySortSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilitySortSearchModelCommon.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilitySortSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantFilterSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantSortSearchModel.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductAvailabilitySearchIntegrationTest.java
> product availability per channel, close #1089

- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductCreateCommandIntegrationTest.java
> create published products, close #1095

- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDataLike.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/ChangeMasterVariant.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> Set product variant as master variant, close #1097

- commercetools-models/src/main/java/io/sphere/sdk/products/queries/SuggestQuery.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/SuggestQueryImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/queries/SuggestQueryIntegrationTest.java
> add fuzzy SuggestQuery, close #1099

- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelProductVariantAvailabilityFacetSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelsProductVariantAvailabilityFacetSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ChannelsProductVariantAvailabilityFacetSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilityFacetSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilityFacetSearchModelCommon.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantAvailabilityFacetSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantFacetSearchModel.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductAvailabilitySearchIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SearchModelImpl.java
> add facets for product availability, close #1103

- commercetools-models/src/main/java/io/sphere/sdk/products/expansion/ProductDataExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/expansion/ProductDataExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/expansion/ProductProjectionExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/expansion/ProductProjectionExpansionModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/expansion/ProductDataExpansionModelTest.java
> all variants expansion paths, close #1094

- commercetools-internal-docs/src/test/java/io/sphere/sdk/meta/AsyncDocumentationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/CompletableFutureUtils.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/utils/CompletableFutureUtilsTest.java
> improve CompletableFutureUtils, close #1123, close #1124, close #1126, close #1128

- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariant.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/DiscountedPriceSortSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/DiscountedPriceSortSearchModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantSortSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ScopedPriceSortSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ScopedPriceSortSearchModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ScopedPriceSearchIntegrationTest.java
originally the issue was to create the facet models for the price scoping. But I don't find sth. in the reference documentation. I tried it out and elastic search gave me weird errors - I don't know if I made an error elastic search had problems or the feature is not there
> sort price scoping, close #1069

- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearch.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchMainIntegrationTest.java
@schleichardt pls review 
https://github.com/commercetools/commercetools-jvm-sdk/blob/master/CONTRIBUTING.md is leading into 404. Is there any contributing guidelines I should follow.
I wrote Integrationtests that works fine. I didn't know if I should also write some Unit-Tests beacuse the code just calls already unit-tested methods
> added bySlug and bySku with integrationtest #1156

- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountCreateCommandIntegrationTest.java
> #1075 ProductDiscountDraftBuilder

- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/LocalizedString.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/models/LocalizedStringTest.java
> Features/1072/language #1072

- commercetools-models/src/main/java/io/sphere/sdk/categories/messages/CategoryCreatedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/messages/CategorySlugChangedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/messages/CategoryCreatedMessageIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/messages/CategorySlugChangedMessageIntegrationTest.java
>  add CategoryCreatedMessage and CategorySlugChangedMessage, close #1025 

- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerCreatedMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/messages/CustomerCreatedMessageIntegrationTest.java
> added CustomerCreatedMessage and test, close #1024

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/GettingStarted.java
- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/SphereClientTuningDocumentation.java
- commercetools-internal-docs/src/main/resources/SpringBatchCommercetoolsClientConfiguration.java
- commercetools-internal-docs/src/main/resources/SpringCommercetoolsConfig.java
- commercetools-java-client/src/test/java/example/BlockingJavaClientInstantiationExample.java
> improve getting started

- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntry.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/commands/updateactions/SetCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/commands/updateactions/SetCustomType.java
- commercetools-models/src/main/java/io/sphere/sdk/types/ResourceTypeIdsSetBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/inventory/InventoryEntryCustomFieldsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/inventory/InventoryEntryFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/types/TypeFixtures.java
> inventory entry custom fields, close #1197

- commercetools-models/src/main/java/io/sphere/sdk/types/commands/updateactions/ChangeEnumValueOrder.java
- commercetools-models/src/main/java/io/sphere/sdk/types/commands/updateactions/ChangeFieldDefinitionOrder.java
- commercetools-models/src/main/java/io/sphere/sdk/types/commands/updateactions/ChangeLocalizedEnumValueOrder.java
- commercetools-models/src/test/java/io/sphere/sdk/types/commands/TypeUpdateCommandIntegrationTest.java
@yanns Can you please review this.
> add missing update actions for types, close #727

- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddExternalImage.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddPrice.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/RemoveImage.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/RemoveVariant.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAttribute.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetPrices.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
@yanns could you review this please.
> Sku can be used to identify a product variant for an update action, close #1023

- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantFacetSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantFilterSearchModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantSortSearchModel.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ScopedPriceSearchIntegrationTest.java
@yanns could you review this, please.
> Missing scoped prices, close #1059

- commercetools-convenience/src/main/java/io/sphere/sdk/sequencegenerators/CustomObjectBigIntegerNumberGenerator.java
- commercetools-convenience/src/main/java/io/sphere/sdk/sequencegenerators/CustomObjectBigIntegerNumberGeneratorConfig.java
- commercetools-convenience/src/main/java/io/sphere/sdk/sequencegenerators/CustomObjectBigIntegerNumberGeneratorConfigBuilder.java
- commercetools-convenience/src/test/java/io/sphere/sdk/sequencegenerators/BigIntegerNumberGeneratorIntegrationTest.java
- commercetools-convenience/src/test/java/io/sphere/sdk/sequencegenerators/CustomObjectBigIntegerNumberGeneratorConfigBuilderTest.java
@yanns @ccsalazarr-commercetools please review
I improved the documentation and added some validations since it is a very important component.
> Number generator changes

- commercetools-models/src/test/java/io/sphere/sdk/jsonnodes/queries/JsonNodeQueryIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/MetaModelQueryDslImpl.java
> fix JsonNodeQuery does not accept URL query parameters, close #1208

- commercetools-models/src/main/java/io/sphere/sdk/carts/CartShippingInfo.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartShippingInfoImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPortionExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPortionExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPriceExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPriceExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/ShippingInfoExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/ShippingInfoExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderShippingInfo.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderShippingInfoImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountInActualCartIntegrationTest.java
@yanns please review, even I merged it to be included into the release
> add CartShippingInfo.getDiscountedPrice and expansion path dsl, close #1225

- commercetools-models/src/main/java/io/sphere/sdk/carts/CustomLineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/ChangeCustomLineItemMoney.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/ChangeCustomLineItemQuantity.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
> change quantity custom line item, close #1195

- commercetools-models/src/main/java/io/sphere/sdk/carts/ExternalLineItemTotalPrice.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/ExternalLineItemTotalPriceImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetLineItemTotalPrice.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
> add setLineItemTotalPrice update action, close #1206

- commercetools-internal-docs/src/test/java/introspection/rules/ResourceDraftBuildersCanBeCreatedByDrafts.java
- commercetools-models/src/main/java/io/sphere/sdk/models/Asset.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetDimensions.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetDimensionsImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetDraftImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetSource.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetSourceBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AssetSourceImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariant.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraftImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddAsset.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/ChangeAssetName.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/ChangeAssetOrder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/RemoveAsset.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetCustomType.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetDescription.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetTags.java
- commercetools-models/src/main/java/io/sphere/sdk/types/ResourceTypeIdsSetBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/types/customupdateactions/SetCustomTypeBase.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/types/TypeFixtures.java
> Feature/1204/assets, close #1204

- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/SphereInternalUtils.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/models/LocalizedStringTest.java
@lauraluiz please review, it belongs to https://github.com/commercetools/commercetools-jvm-sdk/issues/1237
> fix incorrect slugify, close #1237

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/AutoRefreshSphereAccessTokenSupplierImpl.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/RefreshableSphereAccessTokenSupplier.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
@lauraluiz plese review. I did not refactor much, since I am working in another branch on the user agent feature.
> on 401 with supposed to be legitimit token try a token refresh, close #1104

- commercetools-models/src/main/java/io/sphere/sdk/orders/errors/DiscountCodeNonApplicableError.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/errors/PriceChangedError.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/errors/DiscountCodeNonApplicableErrorIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/errors/OutOfStockErrorIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/errors/PriceChangedErrorIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/ShippingMethodFixtures.java
> add PriceChangedError, close #1210

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientModule.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/JavaMoneySphereClientModule.java
- commercetools-sdk-base/src/main/resources/META-INF/services/io.sphere.sdk.client.SphereClientModule
> fix Java money issue #404

- commercetools-models/src/test/java/io/sphere/sdk/client/JsonNodeSphereRequestIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/JsonNodeSphereRequest.java
> Improve JsonNodeSphereRequest, close #447

- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAttribute.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> add factory methods for SetAttribute, close #1077

- commercetools-models/src/main/java/io/sphere/sdk/producttypes/commands/updateactions/ChangeLocalizedEnumValueLabel.java
- commercetools-models/src/main/java/io/sphere/sdk/producttypes/commands/updateactions/ChangePlainEnumValueLabel.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/commands/ProductTypeUpdateCommandIntegrationTest.java
> add changePlainEnumValueLabel and changeLocalizedEnumValueLabel update actions, close #1243

- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/CartExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/CartExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/CartLikeExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/CartLikeExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/CustomLineItemExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/CustomLineItemExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPriceExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPricePerQuantityExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/DiscountedLineItemPricePerQuantityExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/LineItemExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/expansion/LineItemExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/expansion/ProductVariantExpansionModel.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/CartFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/queries/CartQueryIntegrationTest.java
@schleichardt could you review it, please?
> Add lineItem and CustomLineItems expansion models, close #1228

- commercetools-internal-docs/src/test/java/introspection/IntrospectionUtils.java
- commercetools-internal-docs/src/test/java/introspection/rules/PublicConstructorsAreTheExceptionRule.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelIntegrationTest.java
@lauraluiz please review - this PR should be reviewed before the others
> activate aggregations

- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearch.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearchImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/producttypes/ProductTypeDraft.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/MatchingVariantsFlagSearchIntegrationTest.java
@lauraluiz please review, but it is not urgent
> allow flag to disable matching variants

- commercetools-models/src/main/java/io/sphere/sdk/models/Address.java
- commercetools-models/src/main/java/io/sphere/sdk/models/AddressBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/models/AddressTest.java
- commercetools-models/src/test/resources/drafts-tests/customer.json
http://dev.commercetools.com/release-notes.html#release-notes---commercetools-platform---version-release-28102016
> add externalId to Address class

- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ExternalProductDiscountValue.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountValue.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetDiscountedPrice.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
@lauraluiz please review, it is about http://dev.commercetools.com/release-notes.html#release-notes---commercetools-platform---version-release-10112016
> add setDiscountedPrice update action, close #1255

- commercetools-convenience/src/test/java/io/sphere/sdk/meta/CategoryDocumentationIntegrationTest.java
> use blocking wait instead of future.join

- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartLike.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/RoundingMode.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/ChangeTaxRoundingMode.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/TaxRoundingModeIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/PriceUtilsTest.java
@yanns PR is out, can you review it or tell me somebody who should review it?
> Flexible tax rounding mode

- commercetools-models/src/test/java/io/sphere/sdk/carts/TaxRoundingModeIntegrationTest.java
> Add query test for tax rounding mode

- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetedSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/FacetSearchModel.java
@lauraluiz @yanns pls review.
I removed the value switch.
> Remove legacy facet compatibility code

- commercetools-models/src/test/java/io/sphere/sdk/attributestutorial/ProductTypeCreationDemoIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductsScenario1Fixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/products/attributes/AttributesValueMethodIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/SphereJsonUtils.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/SphereInternalUtils.java
@lauraluiz could you review it please?
> Make Attribute.getValueAsStringSet() preserve input order,  close #1294

- commercetools-models/src/main/java/io/sphere/sdk/categories/Category.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryWrapper.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/AddAsset.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/ChangeAssetName.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/ChangeAssetOrder.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/RemoveAsset.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetAssetCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetAssetCustomType.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetAssetDescription.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetAssetSources.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/SetAssetTags.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetDescription.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/CategoryBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/CategoryFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/commands/CategoryUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
@lauraluiz - LMK how does this look to you, and if it makes sense we can create an issue in the commercetools/commercetools-jvm-sdk project.
> Add support for category assets

- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductDraftBuilderTest.java
> Add missing key field to product draft builder, closes #1302

- pom.xml
- sdk-http-ahc-2_0/pom.xml
Tested with sunrise java, closes #1297
> Bumped ahc version and netty version.

- commercetools-convenience/src/main/java/io/sphere/sdk/sequencegenerators/CustomObjectBigIntegerNumberGenerator.java
- commercetools-convenience/src/test/java/io/sphere/sdk/sequencegenerators/BigIntegerNumberGeneratorIntegrationTest.java
> Improved recovery strategy for BigIntegerNumberGenerator.

- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/OrderImportDraftBuilderTest.java
Add missing custom field in draft, impl and builder of orderImport. Close #792
> Add missing custom field in draft, impl and builder of orderImport. Close #792

- commercetools-models/src/main/java/io/sphere/sdk/customers/expansion/CustomerSignInResultExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/expansion/CustomerSignInResultExpansionModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerCreateCommandIntegrationTest.java
@katmatt could you review it please
> add CartExpansionModel in CustomerSignInResultExnasionModel. Close #955

- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductCrudIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/ProductVariantDraftBuilderTest.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/NestedAttributeIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/suppliers/SimpleCottonTShirtProductDraftSupplier.java
- commercetools-models/src/test/java/io/sphere/sdk/suppliers/VariantsCottonTShirtProductDraftSupplier.java
> Fix bug by using a generated abstract builder class.

- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/DraftBuilderGenerator.java
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleWithAbstractBaseClassDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleWithBuilderReturnsInterfaceDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleWithLowerCaseBooleanDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleWithReferenceDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleWithSuperInterfaceDraftBuilder.java.expected
After taking a closer look on the javadoc warnings of our `commercetools-models` project I realized that our new generator produced additional warnings. That's why I slightly changed the generated javadoc  :wink:
> Draft builder generator javadoc fixes

- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingList.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingListDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/commands/updateactions/SetDeleteDaysAfterLastModification.java
- commercetools-models/src/test/java/io/sphere/sdk/shoppinglists/commands/ShoppingListCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shoppinglists/commands/ShoppingListUpdateCommandIntegrationTest.java
> Shoppinglist ttl

- commercetools-models/src/main/java/io/sphere/sdk/carts/Cart.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetDeleteDaysAfterLastModification.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
@katmatt could you review it please
> add deleteDaysAfterLastModification to Cart and CartDraft, close #1337

- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantSortSearchModel.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelSortIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
> Product variants sort by sku

- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductCategoriesIdTermFilterSearchModel.java
This fixes the binary compatibility  of the changed class with our previous release.
> Made class binary compatible with previous released version.

- commercetools-convenience/pom.xml
- commercetools-internal-docs/pom.xml
- commercetools-internal-processors/pom.xml
- commercetools-java-client-ahc-1_8/pom.xml
- commercetools-java-client-ahc-1_9/pom.xml
- commercetools-java-client-ahc-2_0/pom.xml
- commercetools-java-client-apache-async/pom.xml
- commercetools-java-client-core/pom.xml
- commercetools-java-client-internal-test/pom.xml
- commercetools-java-client/pom.xml
- commercetools-models/pom.xml
- commercetools-sdk-base/pom.xml
- commercetools-test-lib/pom.xml
- pom.xml
- sdk-http-ahc-1_8/pom.xml
- sdk-http-ahc-1_9/pom.xml
- sdk-http-ahc-2_0/pom.xml
- sdk-http-apache-async/pom.xml
- sdk-http/pom.xml
Added maven profile to aggregate third party licenses.
> Added license to each modules pom.xml.

- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/LineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/expansion/LineItemExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/expansion/LineItemExpansionModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/shoppinglists/expansion/ShoppingListExpansionModelIntegrationTest.java
> Fixed bug and added an integration test for it.

- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceCollectionQueryModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceQueryModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceTierQueryModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceTierQueryModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/queries/ProductQueryIntegrationTest.java
> Tiered prices query model

- commercetools-models/src/test/java/io/sphere/sdk/carts/queries/CartByCustomerIdGetIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodsByCartGetIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodsByLocationGetIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/test/utils/VrapHeaders.java
- commercetools-models/src/test/java/io/sphere/sdk/test/utils/VrapRequestDecorator.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/HttpRequestIntent.java
> Disable vrap validation for failing tests.

- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetSources.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> "setAssetSources" action support for product added.

- commercetools-models/src/main/java/io/sphere/sdk/categories/Category.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/CategoryFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/categories/queries/CategoryQueryIntegrationTest.java
> Adding orderHint to category query

- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java
> Make quantity on stock mandatory.

- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/PagedSearchResult.java
> Add @Nullable annotations and additional javadoc.

- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountValue.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/GiftLineItemCartDiscountValue.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/Cart.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemMode.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/CartDeserializationTest.java
- commercetools-models/src/test/resources/carts/cart-with-gift-line-item.json
- commercetools-models/src/test/resources/carts/cart-with-refused-gifts.json
- commercetools-models/src/test/resources/carts/cart-with-standard-line-item.json
> Add gift line item cart discount

- commercetools-convenience/src/test/java/io/sphere/sdk/queries/QueryExecutionUtilsTest.java
- commercetools-internal-docs/src/test/java/io/sphere/sdk/client/WrappedClientDemo.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/BlockingSphereClientImpl.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClient.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientDecorator.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TestDoubleSphereClientFactory.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/BlockingSphereClientTest.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/NotAnsweringSphereClient.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/QueueSphereClientDecoratorTest.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/TimeoutSphereClientDecoratorTest.java
> creation of getter for sphere config/ project key through SphereClient.

- commercetools-models/src/main/java/io/sphere/sdk/customers/errors/CustomerInvalidCurrentPassword.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerChangePasswordCommandIntegrationTest.java
> Add CustomerInvalidCurrentPassword error class.

- commercetools-java-client-ahc-1_8/pom.xml
> Change scope tor test-lib to test

- commercetools-models/src/test/resources/drafts-tests/product.json
the type ID of a category is "category" and not "tax-category".
> fix category type id

- commercetools-models/src/main/java/io/sphere/sdk/types/CustomFieldsDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/types/CustomFieldsDraftBuilderIntegrationTest.java
@katmatt could you review it please
> Use type.getId() instead of type.getTypeId() in the builder, close #1444

- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/UpdateActionsGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/models/TypeUtils.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/MyResource.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/MyResourceEnum.java
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ChangeResourceEnum.java.expected
@katmatt could you review this please, and maybe do you have an advice for a more "elegant" implementation of the `isEnumType(...)` method?
> Support enum types in update action generator, close #1440

- commercetools-models/src/main/java/io/sphere/sdk/customers/CustomerToken.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerPasswordResetCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/queries/CustomerByEmailTokenGet.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/queries/CustomerByEmailTokenGetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/queries/CustomerByPasswordTokenGet.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/queries/CustomerByPasswordTokenGetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/queries/CustomerEndpoint.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/queries/CustomerByEmailTokenGetIntegrationTest.java
- sdk-http/src/main/java/io/sphere/sdk/http/UriTemplate.java
- sdk-http/src/main/java/io/sphere/sdk/http/UrlBuilder.java
- sdk-http/src/test/java/io/sphere/sdk/http/UrlBuilderTest.java
This closes #1448, closes #1449.
> Customer get by password and email token

- commercetools-models/src/test/java/io/sphere/sdk/categories/commands/CategoryUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/MetaModelUpdateCommandDslBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/MetaModelUpdateCommandDslImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/UpdateCommand.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/UpdateCommandDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/SphereInternalUtils.java
@acbeni could you review it please
> Add plusUpdateActions method to allow more update actions in command, close #1426

- commercetools-models/src/main/java/io/sphere/sdk/products/messages/ProductPublishedMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/products/messages/ProductPublishedMessageIntegrationTest.java
> Initial commit

- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereProjectScope.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereProjectScopeTest.java
@katmatt could you review it, please... But I have a question, is it worthwhile to add the missing scopes into the class?, or is it enough to have the `of(String scope)` factory method?
> Sphere project scope to string, close #1455

- commercetools-models/pom.xml
- pom.xml
@katmatt, now it is generated a report per module and one aggregated report during the package phase. But I didn't execute the check goal, because the build will fail (when there are breaking changes) no matter if the version is updated.
Could you review it please?
> Revapi check goal, close #1432

- .travis.yml
- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
> V1.21.0 fix release notes

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClient.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/SphereClientTest.java
- commercetools-models/src/test/java/io/sphere/sdk/client/SphereClientIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/CorrelationIdGenerator.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/CorrelationIdGeneratorImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereApiConfig.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereApiConfigImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfig.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfigBuilder.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/CorrelationIdGeneratorTest.java
- pom.xml
- sdk-http/src/main/java/io/sphere/sdk/http/HttpHeaders.java
> Add correlation id generator

- pom.xml
> Adding plugins  to help reporting vulnerable dependencies

- commercetools-models/src/main/java/io/sphere/sdk/carts/Cart.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
> Add new SetAnonymousId update action.

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/TokensSupplierTest.java
> Add corelation id to auth requests.

- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethod.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/ShippingMethodFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/commands/ShippingMethodUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodByKeyGetIntegrationTest.java
> Add shipping method get and update by key.

- commercetools-internal-processors/pom.xml
- pom.xml
> Update test dependencies.

- commercetools-models/pom.xml
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/ChangeSubscriptionSqsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/MessageSubscriptionSqsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/SubscriptionMessagingIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/SubscriptionMessagingIntegrationTestSuite.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/commands/SubscriptionDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/commands/SubscriptionUpdateCommandIntegrationTest.java
> Introduce test group for subscription tests

- commercetools-models/src/main/java/io/sphere/sdk/carts/ExternalTaxAmountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/TaxMode.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCartTotalTax.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomLineItemTaxAmount.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetLineItemTaxAmount.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetShippingMethodTaxAmount.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/CartFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
> External tax amount

- commercetools-models/src/main/java/io/sphere/sdk/types/TypeDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/types/TypeDraftBuilderTest.java
> Fixing NPE when using draft builder with empty fields,

- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/MultiBuyLineItemsTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/SelectionMode.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountInActualCartIntegrationTest.java
> Multi buy discount

- commercetools-models/src/main/java/io/sphere/sdk/payments/Payment.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/queries/PaymentByKeyGetIntegrationTest.java
> Add get, update and delete payment by key.

- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/DraftBuilderGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/models/PropertyGenModel.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraft.java
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftDsl.java.expected
- commercetools-models/src/main/java/io/sphere/sdk/types/TypeDraftBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/SphereInternalUtils.java
addin plus methods for draft builders
> Add convenience methods to generated builder classes

- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/BaseAbstractGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/UpdateActionGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/UpdateActionsGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/models/PropertyGenModel.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/UpdateActionGeneratorTest.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/ExampleResourceWithUpdateAction.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/MyResource.java
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ChangeDeprecatedField.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ChangeMyDeprecatedField.java.expected
> Add support for Deprecated annotation to update action generator.

- commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
@katmatt This seems the issue, the tests run on CI runs fine now 👍
> Correcting SSL issue

- commercetools-models/src/test/java/io/sphere/sdk/types/queries/WithCustomQueryModelIntegrationTest.java
@lauraluiz this PR is intended to make the CI tests run once again.
> Fixing ct test related ctp 766

- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/products/PriceDraftBuilderTest.java
> Fix NPE in priceDraftbuilder and add test for it.

- .travis.yml
- pom.xml
> making tests more precise

- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/AbstractBuilderGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/BaseAbstractGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/DraftBuilderGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/HasBuilderGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/ResourceDraftValueGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/ResourceValueImplGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/UpdateActionGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/UpdateActionsGenerator.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/models/PropertyGenModel.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraft.java
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ChangeDeprecatedField.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ChangeMyDeprecatedField.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftDsl.java.expected
> Add support for Deprecated annotation to resource generators

- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/commands/updateactions/SetCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/commands/updateactions/SetCustomType.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/DiscountCodeCustomFieldsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/DiscountCodeFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/types/TypeFixtures.java
> Add custom fields to DiscountCode.

- .travis.yml
- pom.xml
> #1556: activate build profile avadoc-jdk-8u121 by default

- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/LineItemDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/LineItemDraftBuilder.java
> Shoppinglists lineitemdraft

- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/StackingMode.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
> Add new stacking mode property to CartDiscount.

- .travis.yml
With OSGi support i unintentionally deactivated some tests,
with this PR i activated them again.
> Run ignored tests 

- .travis.yml
- README.md
- pom.xml
> Replace OWASP plugin with snyk vulnerability check.

- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/DraftBuilderGenerator.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/DraftBuilderGeneratorTest.java
- commercetools-internal-processors/src/test/java/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftWithNoAttribute.java
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleDraftWithNoAttributeBuilder.java.expected
- commercetools-internal-processors/src/test/resources/io/sphere/sdk/annotations/processors/generators/examples/ExampleWithBuilderReturnsInterfaceDraftBuilder.java.expected
> bug fix to create draft builder for classes with no attributes

- commercetools-models/src/main/java/io/sphere/sdk/producttypes/commands/updateactions/RemoveEnumValues.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/commands/ProductTypeUpdateCommandIntegrationTest.java
> Add new RemoveEnumValues update action.

- commercetools-convenience/src/test/java/io/sphere/sdk/meta/CategoryDocumentationIntegrationTest.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryTree.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryTreeFactory.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryTreeImpl.java
> Add CategoryTree#findByKey()

- README.md
- osgi-support/sdk-osgi-test-campaign/src/main/java/io/sphere/sdk/test/JvmSdkConfigurationFactory.java
- osgi-support/sdk-osgi-test-campaign/src/test/java/io/sphere/sdk/test/DemoOSGiMinimalConfigTest.java
> Enhance OSGi doc

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/AbstractMultiBuyTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/MultiBuyCustomLineItemsTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/MultiBuyLineItemsTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/SelectionMode.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountInActualCartIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/attributes/DefaultProductAttributeFormatterIntegrationTest.java
> Multi-buy discount for custom line items

- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerSignInCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerSignInCommandIntegrationTest.java
- perform-release.sh
> Sign in update product data

- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/CartDiscountFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/CartFixtures.java
cc @acbeni
tests pass on CI: https://pipe.sphere.io/viewLog.html?buildTypeId=spherejvmsdk_test&buildId=421466
> [CTP-770] fix tests that were attaching discounts to codes without requiring them

- osgi-support/sdk-osgi-test-campaign/src/test/java/io/sphere/sdk/test/DemoOSGiMinimalConfigTest.java
Just a small upgrade of our OSGi example.
> Correct the OSGi min requirements

- commercetools-models/src/main/java/io/sphere/sdk/carts/Cart.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartLike.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/TaxCalculationMode.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/TaxCalculationModeIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/client/UserAgentIntegrationTest.java
> add tax calculation mode to our SDK

- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/LineItemDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/LineItemDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/shoppinglists/commands/ShoppingListCreateCommandIntegrationTest.java
> Create shopping list line item by sku

- commercetools-models/src/test/java/io/sphere/sdk/shoppinglists/commands/ShoppingListCreateCommandIntegrationTest.java
just something i missed in the unit test
> Correcting test

- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethod.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/commands/ShippingMethodUpdateCommandIntegrationTest.java
> Add shipping method set predicate update action.

- perform-release.sh
- prepare-release.sh
@katmatt can you please review and merge ? I have already changed TeamCity config to use this repo.
> Adjustments for the automated release.

- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/commands/updateactions/SetCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/commands/updateactions/SetCustomType.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/types/TypeFixtures.java
> document custom fields on cart discounts

- commercetools-java-client-apache-async/pom.xml
This a quick fix for our tests to make travis work again
> trying to get tests back on track

- commercetools-models/src/main/java/io/sphere/sdk/producttypes/ProductType.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/commands/ProductTypeUpdateCommandIntegrationTest.java
> Add an update action to change `attributeConstraint`

- commercetools-models/src/main/java/io/sphere/sdk/products/attributes/EnumLikeAttributeMapperImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/attributes/AttributeDraftTest.java
> Fix reported issue and add unit test.

- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderReturnShipmentStateChangedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderShipmentStateChangedMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderUpdateCommandIntegrationTest.java
> Add order shipment state change messages.

- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraftDsl.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/commands/DiscountCodeCreateCommandIntegrationTest.java
> Discount Codes: add `validFrom`/`validUntil` 

- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountUpdateCommandIntegrationTest.java
> ProductDiscount Valid From Until

- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/PagedSearchResult.java
> PagedSearchResult.empty() missing

- pom.xml
> Update ahc version

- commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
> Minimize search tests failures.

- commercetools-models/src/main/java/io/sphere/sdk/taxcategories/TaxCategory.java
- commercetools-models/src/test/java/io/sphere/sdk/taxcategories/TaxCategoryIntegrationTest.java
> Add byKey method to TaxCategoryQuery

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryDraftBuilder.java
> Reference a category parent by its key

- commercetools-models/src/main/java/io/sphere/sdk/orders/expansion/OrderExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/expansion/OrderExpansionModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderFromCartCreateCommandIntegrationTest.java
> add state expansion to orderExpansionModel.

- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/PagedQueryResult.java
> Insuring backward compatibility

- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCodeDraftDsl.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/commands/DiscountCodeCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/commands/DiscountCodeUpdateCommandIntegrationTest.java
Support for our backend feature
Closes #1674
> Added discount code groups

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
Release notes for issues
https://github.com/commercetools/commercetools-jvm-sdk/pull/1680
https://github.com/commercetools/commercetools-jvm-sdk/pull/1676
> Update release note for PRs

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/ParcelItemsUpdatedMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderUpdateCommandIntegrationTest.java
> insert field deliveryID in ParcelItemsUpdated Message

- commercetools-java-client-core/pom.xml
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SolutionInfoService.java
> Solution info not working

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SolutionInfoService.java
- osgi-support/commercetools-tests-fragment/pom.xml
Solution info doesn't work quite well with Sunrise, this is a quick fix
> Solution Info bug

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/CoreProductVariantQueryModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductVariantQueryModelImpl.java
> ProductVariantQueryModel is missing method for key property

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/CartDiscountFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/queries/QueryAllIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/FuzzyLevelIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/PriceSelectionIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ScopedPriceSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/reviews/ReviewProductProjectionSearchIntegrationTest.java
- commercetools-sdk-base/pom.xml
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/MoneyRepresentation.java
- commercetools-sdk-base/src/main/java/javax/money/spi/Bootstrap.java
- commercetools-sdk-base/src/main/java/javax/money/spi/OSGiPriorityAwareServiceProvider.java
- commercetools-sdk-base/src/main/resources/META-INF/services/javax.money.spi.ServiceProvider
- osgi-support/sdk-osgi-test-campaign/pom.xml
This an error that appear from time to time, related to the classloader use.
> Javamoney error fix

- perform-release.sh
- prepare-release.sh
> Fix or patch release scrript.

- README.md
- commercetools-convenience/pom.xml
- commercetools-internal-docs/pom.xml
- commercetools-internal-processors/pom.xml
- commercetools-java-client-ahc-1_8/pom.xml
- commercetools-java-client-ahc-1_9/pom.xml
- commercetools-java-client-ahc-2_0/pom.xml
- commercetools-java-client-apache-async/pom.xml
- commercetools-java-client-core/pom.xml
- commercetools-java-client-internal-test/pom.xml
- commercetools-java-client/pom.xml
- commercetools-models/pom.xml
- commercetools-sdk-base/pom.xml
- commercetools-test-lib/pom.xml
- osgi-support/commercetools-tests-fragment/pom.xml
- osgi-support/mirror-subclass-plugin/pom.xml
- osgi-support/pom.xml
- osgi-support/sdk-osgi-test-campaign/pom.xml
- pom.xml
- sdk-http-ahc-1_8/pom.xml
- sdk-http-ahc-1_9/pom.xml
- sdk-http-ahc-2_0/pom.xml
- sdk-http-apache-async/pom.xml
- sdk-http/pom.xml
> Merge 1.29.1

- commercetools-convenience/pom.xml
- commercetools-internal-docs/pom.xml
- commercetools-internal-processors/pom.xml
- commercetools-java-client-ahc-1_8/pom.xml
- commercetools-java-client-ahc-1_9/pom.xml
- commercetools-java-client-ahc-2_0/pom.xml
- commercetools-java-client-apache-async/pom.xml
- commercetools-java-client-core/pom.xml
- commercetools-java-client-internal-test/pom.xml
- commercetools-java-client/pom.xml
- commercetools-models/pom.xml
- commercetools-sdk-base/pom.xml
- commercetools-test-lib/pom.xml
- osgi-support/commercetools-tests-fragment/pom.xml
- osgi-support/mirror-subclass-plugin/pom.xml
- osgi-support/pom.xml
- osgi-support/sdk-osgi-test-campaign/pom.xml
- sdk-http-ahc-1_8/pom.xml
- sdk-http-ahc-1_9/pom.xml
- sdk-http-ahc-2_0/pom.xml
- sdk-http-apache-async/pom.xml
- sdk-http/pom.xml
> Fix bootstrapping of our JVM SDK.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerAddressAddedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerAddressChangedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerAddressRemovedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerCompanyNameSetMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerDateOfBirthSetMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerEmailChangedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerEmailVerifiedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerGroupSetMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerCreateEmailTokenCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerUpdateCommandIntegrationTest.java
> Add documentation for customer messages

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartEndpoint.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/CartEndpoint.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/CartReplicationCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/CartReplicationDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/queries/CartByCustomerIdGetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/queries/CartEndpoint.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartReplicationIntegrationTest.java
> Cart replication command.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/Reference.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/ReferenceImpl.java
- osgi-support/sdk-osgi-test-campaign/pom.xml
- pom.xml
> Update jackson version

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductLike.java
> Make ProductLike interface public.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/producttypes/ProductType.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/commands/ProductTypeUpdateCommandIntegrationTest.java
Adding support for our new backend actions.
closes #1727
> Renaming update action on product types

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAssetCustomType.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
Correct method name typo
closes #1702
> Correct method name typo

- commercetools-convenience/src/main/java/io/sphere/sdk/sequencegenerators/CustomObjectBigIntegerNumberGeneratorConfigBuilder.java
- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/generators/AbstractBuilderGenerator.java
- commercetools-models/pom.xml
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/messages/CustomerCompanyNameSetMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/Payment.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/PaymentDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetImageLabel.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/annotations/HasUpdateAction.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/annotations/ResourceInfo.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/PagedQueryResult.java
> Javadoc include generated sources

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/OSGiSupportDocumentation.java
- src/main/javadoc/overview.html
> Add OSGi doc

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/extensions/ExtensionResourceType.java
- commercetools-models/src/test/java/io/sphere/sdk/extensions/commands/ExtensionUpdateCommandIntegrationTest.java
> dd support for our new backend issue

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/ItemShippingDetails.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/ItemShippingTarget.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/Order.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/CartMultipleShippingAddressesIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/OrderFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/OrderMultipleShippingAddressesIntegrationTest.java
> Order updates multiple shipping addresses

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/Payment.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/PaymentDraft.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentUpdateCommandIntegrationTest.java
> Payment anonymous

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/SphereJsonUtils.java
> Add patch to configure an existing jackson object mapper.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- pom.xml
> Update Jackon Version

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/Cart.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/RemoveLineItem.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/CartMultipleShippingAddressesIntegrationTest.java
> Field `shippingDetailsToRemove` is missing on class RemoveLineItem

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/CustomerDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/CustomerDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/CustomerDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetCustomerGroup.java
> Customer group key usable on carts and customers

- commercetools-internal-docs/pom.xml
- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-java-client-internal-test/src/main/java/io/sphere/sdk/client/HttpClientAdapterTest.java
- pom.xml
- sdk-http-ahc-2_0/pom.xml
> Async http client and spring boot 2 version clash

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-internal-processors/src/main/java/io/sphere/sdk/annotations/processors/DeleteCommandEndpointAnnotationProcessor.java
- commercetools-internal-processors/src/main/resources/commercetools-jvm-sdk-processor-templates/commands/deleteCommandImplementation.hbs
- commercetools-internal-processors/src/main/resources/commercetools-jvm-sdk-processor-templates/commands/deleteCommandInterface.hbs
- commercetools-models/src/main/java/io/sphere/sdk/carts/Cart.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/Customer.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/commands/CustomObjectDeleteCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/commands/CustomObjectDeleteCommandImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/Order.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/Payment.java
- commercetools-models/src/main/java/io/sphere/sdk/reviews/Review.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingList.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/commands/CustomObjectDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/commands/DiscountCodeDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/reviews/ReviewFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/reviews/commands/ReviewDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shoppinglists/commands/ShoppingListDeleteCommandIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/annotations/HasDeleteCommand.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/MetaModelByIdDeleteCommandBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/commands/MetaModelByIdDeleteCommandImpl.java
> Data erasure support

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-internal-docs/src/test/java/introspection/rules/ImplClassesAreForPackageScopeRule.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/products/HighPrecisionMoneyTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/MoneyTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/CentPrecisionMoneyRepresentation.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/HighPrecisionMoneyRepresentation.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/MoneyDeserializer.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/MoneyRepresentation.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/MoneySerializer.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/HighPrecisionMoneyImpl.java
> High precision prices

- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/StackingMode.java
> Stacking mode doc update

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/Customer.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/queries/CustomerQueryIntegrationTest.java
> Query customers by middlename and title

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/MessageSubscriptionPayload.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/MessageSubscriptionPayloadImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/PayloadNotIncluded.java
> Subscription not included reason

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/ProductVariantImportDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderImportCommandIntegrationTest.java
related to #1766
The release notes will be done separately
> Fixing price bug

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/categories/commands/updateactions/ChangeParent.java
> Use resourceidentifier to change category parent

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/Destination.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/PubSubDestination.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/SubscriptionFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/commands/SubscriptionCreateCommandIntegrationTest.java
> Add PubSub destination support

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/ResourceCreatedPayload.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/ResourceDeletedPayload.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/ResourceUpdatedPayload.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/ChangeSubscriptionSqsIntegrationTest.java
> Add modified at to payloads

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscount.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountUpdateCommandIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/annotations/HasUpdateAction.java
> Add setvalidfromanduntil update action to product discount

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderFromCartDraft.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderFromCartCreateCommandIntegrationTest.java
> Create Order from Cart: be able to set State

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/producttypes/commands/updateactions/AddAttributeDefinition.java
> ProductType#AddAttributeDefinition update action is not according to commercetools API spec

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/Subscription.java
- commercetools-models/src/main/java/io/sphere/sdk/subscriptions/SubscriptionHealthStatus.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/commands/SubscriptionUpdateCommandIntegrationTest.java
> Add subscription health  check to subscription.

- commercetools-models/src/test/java/io/sphere/sdk/extensions/commands/AbstractExtensionIntegrationTest.java
> Fixing tests

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/commands/DiscountCodeUpdateCommandIntegrationTest.java
> #1795 set valid from and until

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderDeletedMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/messages/OrderMessagesIntegrationTest.java
> Add new OrderDeletedMessage.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetShippingRateInput.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/ShippingRateCartValueIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/ShippingRateClassificationIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/ShippingRateScoreIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/commands/SubscriptionCreateCommandIntegrationTest.java
There was a bug report that I couldn't confirm because the tests were not conclusive. I have improved them adding assertions in order to guarantee there's no bug present in the shipping rate inputs.
The output was that we had indeed a bug in the field name.
> Fix field name typo in cart update action SetShippingRateInput

- commercetools-models/src/main/java/io/sphere/sdk/products/SuggestionResultImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/SuggestionResultTest.java
> SuggestionResultImpl does not correctly handle searchKeywords prefix

- commercetools-models/src/main/java/io/sphere/sdk/products/SuggestionResultImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/types/CustomFieldsDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/products/SuggestionResultTest.java
- commercetools-models/src/test/java/io/sphere/sdk/types/CustomFieldsDraftBuilderIntegrationTest.java
> Custom field drafts

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/states/State.java
- commercetools-models/src/main/java/io/sphere/sdk/taxcategories/TaxCategory.java
- commercetools-models/src/main/java/io/sphere/sdk/types/Type.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/ChangeSubscriptionTest.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/SubscriptionFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/subscriptions/commands/SubscriptionCreateCommandIntegrationTest.java
Follow up for a backend issue
Closes #1813
> Change Subscriptions support ten more resource types

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereProjectScope.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereProjectScopeTest.java
> Add new scopes

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/Order.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderCustomerGroupSetMessge.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/OrderDeserializationTest.java
- commercetools-models/src/test/resources/order/order-with-refused-gift.json
> Set line item price

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/MessagesConfiguration.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/MessagesConfigurationDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/MessagesConfigurationDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/Project.java
- commercetools-models/src/test/java/io/sphere/sdk/projects/commands/ProjectUpdateActionsIntegrationTest.java
> New messages settings for project.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSortSearchModel.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelSortIntegrationTest.java
Add new sort parameter for our product projection search endpoint.
Closes #1826
> Product projection search - explicit sorting by score

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/messages/ProductPriceDiscountUpdate.java
- commercetools-models/src/main/java/io/sphere/sdk/products/messages/ProductPriceDiscountsSetMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/products/messages/ProductPriceExternalDiscountSetMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> Sort by score.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethodDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethodDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/commands/updateactions/ChangeTaxCategory.java
> Update tax category by key

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/messages/UserProvidedIdentifiers.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/messages/CustomerCreatedMessageIntegrationTest.java
Add new field to a message.
Closes #1838
> #1838 customer number in user provided identifiers

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethodDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethodDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ZoneRateDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/commands/updateactions/AddShippingRate.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/commands/updateactions/AddZone.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/commands/updateactions/RemoveShippingRate.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/commands/updateactions/RemoveZone.java
- commercetools-models/src/main/java/io/sphere/sdk/zones/Zone.java
- commercetools-models/src/main/java/io/sphere/sdk/zones/ZoneDraft.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/commands/ShippingMethodCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/zones/commands/ZoneCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/zones/commands/ZoneUpdateCommandIntegrationTest.java
> Add zone key

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountValue.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/GiftLineItemCartDiscountValue.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
> update following rules

- PULL_REQUEST_TEMPLATE.md
- commercetools-models/src/test/java/io/sphere/sdk/apiclient/ApiClientFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/client/TokensFacadeIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
This would allow us to keep an updated api reference.
Closes #
> Make update Api reference part of our process

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartShippingInfo.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CustomLineItemDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CustomLineItemDraftImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddCustomLineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomShippingMethod.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetShippingMethod.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/InventoryEntryDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/commands/updateactions/SetSupplyChannel.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderShippingInfo.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/ShippingInfoImportDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetTaxCategory.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderImportCommandIntegrationTest.java
> change some references to resource identifiers

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddLineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/UpdateSyncInfo.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftDsl.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/LineItemDraftBuilderIntegrationTest.java
support for backend changes
Closes #1857
> Consolidate referencing channels in modifications

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClient.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClientDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClientDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClientImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/apiclient/ApiClientCommandIntegrationTest.java
> #1858 ttl for api client

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddLineItem.java
> #1755 remove deprecated annotations from add line item

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductVariantDraftBuilder.java
> #1701 product variant draft mark nullable

- pom.xml
> Added new contributor.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddVariant.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> Added assets field to AddVariant, updated tests.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/expansion/CustomObjectExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/expansion/CustomObjectExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectByIdGet.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectByIdGetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectByKeyGet.java
- commercetools-models/src/main/java/io/sphere/sdk/customobjects/queries/CustomObjectByKeyGetImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/CustomObjectFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/queries/CustomObjectByIdGetIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/queries/CustomObjectByKeyGetIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/customobjects/queries/MyCustomClass.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/SphereJsonUtils.java
> #1777 expansion model missing

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/attributes/Attribute.java
- commercetools-models/src/main/java/io/sphere/sdk/products/attributes/ReferenceInternalObjectMapper.java
- commercetools-models/src/main/java/io/sphere/sdk/products/attributes/ReferenceInternalSerializer.java
- commercetools-models/src/test/java/io/sphere/sdk/products/attributes/AttributeFromReferenceTest.java
> #1868 set of references expansion

- commercetools-sdk-base/pom.xml
junit should not be included in the production code
> junit as test dependency

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-internal-processors/src/main/resources/commercetools-jvm-sdk-processor-templates/commands/updateCommandInterface.hbs
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/ProductUpdateCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java
> #1609 add vararg factory method to update commands

- commercetools-models/src/main/java/io/sphere/sdk/orderedits/commands/OrderEditApplyCommand.java
- commercetools-models/src/main/java/io/sphere/sdk/orderedits/expansion/OrderEditExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/orderedits/expansion/OrderEditExpansionModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/expansion/OrderExpansionModel.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/expansion/OrderExpansionModelImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/orderedit/OrderEditFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/orderedit/commands/OrderEditApplyCommandIntegrationTest.java
> #1879 apply order edit

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
> #1886 order edit docs

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductCatalogData.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductCatalogDataImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductCreateCommandIntegrationTest.java
> #1614 get current product

- commercetools-models/src/test/java/io/sphere/sdk/categories/CategoriesPagingIntegrationTest.java
The offset needs to be lowered, as we'd like to stop new projects from making queries with such huge offsets.
Closes #
> Lower offset limit

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-internal-processors/src/main/resources/commercetools-jvm-sdk-processor-templates/commands/updateCommandInterface.hbs
> #1894 unchecked varargs

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/ExternalOAuth.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/Project.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/ProjectImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/projects/commands/ProjectUpdateActionsIntegrationTest.java
> #1895 add support for external auth

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/extensions/Extension.java
- commercetools-models/src/main/java/io/sphere/sdk/extensions/ExtensionDraft.java
- commercetools-models/src/test/java/io/sphere/sdk/extensions/commands/AbstractExtensionIntegrationTest.java
> #1896 extension timeout

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerCreatePasswordTokenCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerCreatePasswordTokenCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/errors/SphereExceptionIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/projects/commands/ProjectUpdateActionsIntegrationTest.java
> #1900 customer create password token ttl missing

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/extensions/AuthorizationHeaderAuthentication.java
- commercetools-models/src/main/java/io/sphere/sdk/extensions/HttpDestinationAuthentication.java
- commercetools-models/src/test/java/io/sphere/sdk/extensions/commands/HttpDestinationIntegrationTest.java
> #1907 support for authorization header authentication

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddLineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/orderedits/commands/stagedactions/AddLineItem.java
- commercetools-models/src/test/java/io/sphere/sdk/orderedit/commands/stagedactions/OrderEditStagedActionsIntegrationTest.java
…t AddLineItem update action.
Closes #1902
> #1902 add line item structure fix

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/types/commands/updateactions/ChangeEnumValueLabel.java
- commercetools-models/src/main/java/io/sphere/sdk/types/commands/updateactions/ChangeInputHint.java
- commercetools-models/src/main/java/io/sphere/sdk/types/commands/updateactions/ChangeLocalizedEnumValueLabel.java
- commercetools-models/src/test/java/io/sphere/sdk/types/commands/TypeUpdateCommandIntegrationTest.java
> added new update actions to types

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/discountcodes/DiscountCode.java
> #1928 document application version

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/CustomerToken.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/CustomerTokenImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerCreatePasswordTokenCommandIntegrationTest.java
> #1938 customer token missing expires at

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/productdiscounts/ProductDiscountDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/ProductDiscountFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountDeleteCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/commands/ProductDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/productdiscounts/queries/ProductDiscountByKeyGetIntegrationTest.java
> #1935 product discount key

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftDsl.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/CartDiscountFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/commands/CartDiscountUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/queries/CartDiscountByKeyGetIntegrationTest.java
> #1927 cart discount key

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/search/PagedSearchResult.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/search/PagedSearchResultTest.java
> #1940 paged search result serialization

- commercetools-models/src/test/java/io/sphere/sdk/customers/queries/CustomerQueryIntegrationTest.java
> added integration test for customer key predicate

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/GettingStarted.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientFactory.java
- commercetools-java-client/src/test/java/example/JavaClientInstantiationExampleInUSA.java
> Add doc to use USA based projects

- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/commands/DiscountCodeDeleteCommandIntegrationTest.java
These tests failed from time to time on our internal TeamCity CI server.
> Improve test by using a random key.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/messages/ProductAddedToCategoryMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/products/messages/ProductRemovedFromCategoryMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/products/messages/ProductAddedToCategoryMessageIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/messages/ProductRemovedFromCategoryMessageIntegrationTest.java
> #1965 add new messages for product updates

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/commands/ProductImageUploadCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductImageUploadCommandIntegrationTest.java
> #1968 product image upload command.with content type fix

- commercetools-models/src/test/java/io/sphere/sdk/channels/queries/ChannelQueryIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetedSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/reviews/ReviewProductProjectionSearchIntegrationTest.java
> Ignore failing search tests

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/CategoriesWithAncestorsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ExistsAndMissingFilterIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/FacetResultTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/FullLocaleSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/FuzzyLevelIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/MatchingVariantsFlagSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/PriceSelectionIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductAttributeSortSearchModelTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductAvailabilitySearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductCategoriesIdTermFilterSearchModelIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchBuilderTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchFacetedSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchFacetsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchFiltersIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchMainIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetedSearchIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFacetsIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelFiltersIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchModelSortIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchSortIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ScopedPriceSearchIntegrationTest.java
- sdk-http/src/main/java/io/sphere/sdk/http/HttpHeaders.java
> Ignore search tests

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- sdk-http/src/main/java/io/sphere/sdk/http/HttpHeaders.java
> get header case insensitive

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderImportDraftImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderImportCommandIntegrationTest.java
> #1978 store in order import

- pom.xml
The new update fixes a bug that's affecting us: https://github.com/commercetools/commercetools-sync-java/issues/441
> Bump jackson to 2.10.0

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereProjectScope.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereProjectScopeTest.java
> #1989 add new oauth scopes

- pom.xml
> updagraded jackson to the latest version

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/AddStore.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/RemoveStore.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetStores.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerUpdateCommandIntegrationTest.java
> #1993 missing update actions for stores on customer

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderMessage.java
> Order message deserialization

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/payments/TransactionDraftDsl.java
> TransactionDraftDsl is now public

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartsConfiguration.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartsConfigurationImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/ShoppingListsConfiguration.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/ShoppingListsConfigurationImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/Project.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/ProjectImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/projects/commands/ProjectIntegrationTest.java
> added carts and shopping lists configuration to projects.

- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/ReferenceMixIn.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/json/SphereJsonUtils.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/KeyReference.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/KeyReferenceImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/Reference.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/ReferenceImpl.java
> replace JsonProperty annotation for references with MixIn annotation

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/WithinCircleQueryPredicate.java
- commercetools-sdk-base/src/test/java/io/sphere/sdk/queries/WithinCircleQueryPredicateTest.java
> Update README and ReleaseNotes.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/taxcategories/ExternalTaxRateDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/taxcategories/ExternalTaxRateDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/taxcategories/ExternalTaxRateDraftImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/ExternalTaxRatesIntegrationTest.java
> Add missing includedInPrice property to ExternalTaxRateDraft.

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethod.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethodDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingMethodDraftBuilder.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/ShippingMethodFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/commands/ShippingMethodCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/commands/ShippingMethodUpdateCommandIntegrationTest.java
Closes https://github.com/commercetools/commercetools-jvm-sdk/issues/2024
> Support shipping method localized description

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/inventory/messages/InventoryEntryCreatedMessage.java
Closes https://github.com/commercetools/commercetools-jvm-sdk/issues/2031
> support message for inventory entry created

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodsByOrderEditGet.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodsByOrderEditGetImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodsByOrderEditGetIntegrationTest.java
Closes https://github.com/commercetools/commercetools-jvm-sdk/issues/2032
> Support shippingmethods location orderedit

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionByIdGet.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionByIdGetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionByKeyGet.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionByKeyGetImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionQuery.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductProjectionQueryImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelection.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelectionBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelectionDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/PriceSelectionQueryParameters.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearch.java
- commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSearchImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/queries/ProductProjectionQueryIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchMainIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/LocaleSelection.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/LocaleSelectionBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/LocaleSelectionDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/LocaleSelectionQueryParameters.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/LocaleSelectionRequestDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/StoreSelection.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/StoreSelectionBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/StoreSelectionDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/StoreSelectionQueryParameters.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/selection/StoreSelectionRequestDsl.java
> TASK Prepare release 1.52.0

- commercetools-convenience/pom.xml
- commercetools-internal-docs/pom.xml
- commercetools-internal-processors/pom.xml
- commercetools-java-client-ahc-1_8/pom.xml
- commercetools-java-client-ahc-1_9/pom.xml
- commercetools-java-client-ahc-2_0/pom.xml
- commercetools-java-client-ahc-2_5/pom.xml
- commercetools-java-client-apache-async/pom.xml
- commercetools-java-client-core/pom.xml
- commercetools-java-client-internal-test/pom.xml
- commercetools-java-client/pom.xml
- commercetools-models/pom.xml
- commercetools-sdk-base/pom.xml
- commercetools-test-lib/pom.xml
- osgi-support/commercetools-tests-fragment/pom.xml
- osgi-support/mirror-subclass-plugin/pom.xml
- osgi-support/pom.xml
- osgi-support/sdk-osgi-test-campaign/pom.xml
- pom.xml
- sdk-http-ahc-1_8/pom.xml
- sdk-http-ahc-1_9/pom.xml
- sdk-http-ahc-2_0/pom.xml
- sdk-http-ahc-2_5/pom.xml
- sdk-http-apache-async/pom.xml
- sdk-http/pom.xml
This reverts commit e38996eed1ee0e9e81b2b2967c0a99f16832412c.
Closes #
> Revert "Set next development version 1.54.0-SNAPSHOT"

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/Order.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetStore.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderStoreSetMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/commands/OrderUpdateCommandIntegrationTest.java
Closes https://github.com/commercetools/commercetools-jvm-sdk/issues/2030
> support setStore and message for order

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/projects/error/LanguageUsedInStores.java
> add LanguageUsedInStore error

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/Store.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/StoreDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/commands/updateactions/AddDistributionChannel.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/commands/updateactions/RemoveDistributionChannel.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/commands/updateactions/SetDistributionChannels.java
- commercetools-models/src/test/java/io/sphere/sdk/stores/commands/StoreUpdateCommandIntegrationTest.java
Closes https://github.com/commercetools/commercetools-jvm-sdk/issues/2036
> Support distributionChannel in Store and related update commands

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/CurrencyUtils.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/HighPrecisionMoneyImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/MoneyImpl.java
> only create one CurrencyProvider instance

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceCollectionQueryModel.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceCollectionQueryModelImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/PriceQueryModel.java
> fix type for PriceCollectionQueryModel channel

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingListDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/ShoppingListDraftBuilder.java
change customer to ResourceIdentifier for shopping list draft
Closes #2052
Closes #
> change state to ResourceIdentifier for product draft

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/error/MissingRoleOnChannelError.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/error/ProjectNotConfiguredForLanguagesError.java
> Support error code for store

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/ChangeAddress.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/RemoveAddress.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetDefaultBillingAddress.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetDefaultShippingAddress.java
> Support address by key for customer

- commercetools-sdk-base/pom.xml
- perform-release.sh
- pom.xml
> fix buildreorder library version alphabeticallyadd mirror-class-plugin to release

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/AddBillingAddressId.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/AddShippingAddressId.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/RemoveBillingAddressId.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/RemoveShippingAddressId.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetDefaultBillingAddress.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetDefaultShippingAddress.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerUpdateCommandIntegrationTest.java
> Add and Remove shipping/billing address by key

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemDraftDsl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/AddLineItem.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
> support addedAt to Lineitem in the cart

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/Store.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/StoreDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/commands/updateactions/AddSupplyChannel.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/commands/updateactions/RemoveSupplyChannel.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/commands/updateactions/SetSupplyChannels.java
- commercetools-models/src/test/java/io/sphere/sdk/stores/commands/StoreUpdateCommandIntegrationTest.java
> Add supplyChannel in store and update actions related

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItem.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/LineItemImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java
Closes #2059# Description
Closes #
> add lastModifiedAt to LineItem

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/commands/updateactions/SetCustomerGroup.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/updateactions/SetCustomerGroup.java
- commercetools-models/src/main/java/io/sphere/sdk/orderedits/commands/stagedactions/SetCustomerGroup.java
- commercetools-models/src/main/java/io/sphere/sdk/reviews/commands/updateactions/SetCustomer.java
- commercetools-models/src/main/java/io/sphere/sdk/shoppinglists/commands/updateactions/SetCustomer.java
- commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/queries/SuggestQueryIntegrationTest.java
> support ResourceIdentifier to set customer groups

- commercetools-models/src/test/java/io/sphere/sdk/cartdiscounts/CartDiscountFixtures.java
- commercetools-models/src/test/java/io/sphere/sdk/discountcodes/DiscountCodeFixtures.java
> fix test for create cart with cart discount

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftDsl.java
Support ResourceIdentifier on CustomerGroup in PriceDraft
https://github.com/commercetools/commercetools-jvm-sdk/issues/2120
- Modify PriceDraft, PriceDraftBuilder and PriceDraftDsl
- Add remarks in ReleaseNotes.java
> Support resourceidentifier customer group

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/products/PriceDraftDsl.java
- commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductCreateCommandIntegrationTest.java
> Discounted pricedraft

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClient.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplier.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/UserAgentUtils.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/TokensSupplierTest.java
> add option to customize user agent in tokensupplier

- commercetools-sdk-base/src/main/java/io/sphere/sdk/models/SphereException.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/utils/SphereInternalLogger.java
- commercetools-sdk-base/src/test/resources/logback-test.xml
> add logger error in retry method

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/carts/CartDraftDsl.java
> support externalTaxRateForShippingMethod in the cart

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SolutionInfo.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/UserAgentUtils.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/TokensSupplierTest.java
- commercetools-models/src/test/java/io/sphere/sdk/client/TokensSupplierImplTest.java
- commercetools-models/src/test/java/io/sphere/sdk/client/UserAgentIntegrationTest.java
- commercetools-sdk-base/src/main/templates/io/sphere/sdk/meta/BuildInfo.java.template
- commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTestHttpClient.java
- sdk-http-apache-async/src/main/java/io/sphere/sdk/http/ApacheHttpClientAdapterImpl.java
> modified user agent

- README.md
> SDK Deprecation Announcement

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/customers/commands/CustomerInStoreChangePasswordCommand.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerInStoreChangePasswordCommandIntegrationTest.java
> Customer InStore Change Password command

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderStateTransitionMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/messages/StoreCreatedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/stores/messages/StoreDeletedMessage.java
- commercetools-models/src/test/java/io/sphere/sdk/inventory/commands/InventoryEntryCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/stores/commands/StoreCreateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/stores/commands/StoreDeleteCommandIntegrationTest.java
> support store messages for create and delete commands

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/shippingmethods/ShippingRatePriceTier.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/OrderDeserializationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/orders/queries/OrderQueryIntegrationTest.java
> reproduce and fix serialization issue for shipping rate tiers

- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/AutoRefreshSphereAccessTokenSupplierImpl.java
- commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java
- commercetools-java-client-core/src/test/java/io/sphere/sdk/client/AutoRefreshSphereAccessTokenSupplierImplTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SuspendedProjectException.java
Project suspension is not handled as fatal anymore
> Project suspended test

- .github/workflows/release.yml
- .mvn/wrapper/maven-wrapper.properties
- perform-release.sh
- prepare-release.sh
> Fix GH release

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-internal-docs/src/test/java/introspection/rules/ImplClassesAreForPackageScopeRule.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClient.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClientDraft.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClientDraftBuilder.java
- commercetools-models/src/main/java/io/sphere/sdk/apiclient/ApiClientImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/orderedits/commands/stagedactions/SetDeliveryCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/orderedits/commands/stagedactions/SetDeliveryCustomType.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/Delivery.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/AddDelivery.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetDeliveryCustomField.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/commands/updateactions/SetDeliveryCustomType.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/messages/OrderPaymentAddedMessage.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductByIdHead.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductByIdHeadImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductByKeyHead.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductByKeyHeadImpl.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductsHead.java
- commercetools-models/src/main/java/io/sphere/sdk/products/queries/ProductsHeadImpl.java
- commercetools-models/src/test/java/io/sphere/sdk/payments/queries/PaymentQueryIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/products/queries/SuggestQueryIntegrationTest.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/Head.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/HeadDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/MetaModelHeadDsl.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/MetaModelHeadDslBuilder.java
- commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/MetaModelHeadDslImpl.java
> LTS Maintainance

- .github/workflows/ci.yml
- commercetools-models/pom.xml
- commercetools-models/src/test/resources/logback-test.xml
- commercetools-test-lib/pom.xml
- commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java
- licenses/commercetools-convenience/index.json
- licenses/commercetools-internal-docs/index.json
- licenses/commercetools-internal-processors/index.json
- licenses/commercetools-java-client-ahc-1_8/index.json
- licenses/commercetools-java-client-ahc-1_9/index.json
- licenses/commercetools-java-client-ahc-2_0/index.json
- licenses/commercetools-java-client-ahc-2_12/index.json
- licenses/commercetools-java-client-ahc-2_5/index.json
- licenses/commercetools-java-client-apache-async/index.json
- licenses/commercetools-java-client-core/index.json
- licenses/commercetools-java-client-internal-test/index.json
- licenses/commercetools-java-client/index.json
- licenses/commercetools-models/index.json
- licenses/commercetools-sdk-base/index.json
- licenses/commercetools-test-lib/index.json
- licenses/index.json
- licenses/sdk-http-ahc-1_8/index.json
- licenses/sdk-http-ahc-1_9/index.json
- licenses/sdk-http-ahc-2_0/index.json
- licenses/sdk-http-ahc-2_12/index.json
- licenses/sdk-http-ahc-2_5/index.json
- licenses/sdk-http-apache-async/index.json
- licenses/sdk-http/index.json
- pom.xml
> V2 compat test

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/orders/OrderFromCartDraft.java
> support custom field in the order from cart draft

- README.md
> Extending Maintenance phase of the SDK till end of 2023

- commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
- commercetools-models/src/main/java/io/sphere/sdk/productselections/commands/updateactions/AddProduct.java
- commercetools-models/src/test/java/io/sphere/sdk/productselections/commands/ProductSelectionUpdateCommandTest.java
- licenses/commercetools-convenience/index.json
- licenses/commercetools-internal-docs/index.json
- licenses/commercetools-internal-processors/index.json
- licenses/commercetools-java-client-ahc-1_8/index.json
- licenses/commercetools-java-client-ahc-1_9/index.json
- licenses/commercetools-java-client-ahc-2_0/index.json
- licenses/commercetools-java-client-ahc-2_12/index.json
- licenses/commercetools-java-client-ahc-2_5/index.json
- licenses/commercetools-java-client-apache-async/index.json
- licenses/commercetools-java-client-core/index.json
- licenses/commercetools-java-client-internal-test/index.json
- licenses/commercetools-java-client/index.json
- licenses/commercetools-models/index.json
- licenses/commercetools-sdk-base/index.json
- licenses/commercetools-test-lib/index.json
- licenses/index.json
- licenses/sdk-http-ahc-1_8/index.json
- licenses/sdk-http-ahc-1_9/index.json
- licenses/sdk-http-ahc-2_0/index.json
- licenses/sdk-http-ahc-2_12/index.json
- licenses/sdk-http-ahc-2_5/index.json
- licenses/sdk-http-apache-async/index.json
Renaming property in the AddProduct update action
Closes #
> Rename property addproduct

- commercetools-models/src/main/java/io/sphere/sdk/products/attributes/ReferenceAttributeType.java
- commercetools-models/src/main/java/io/sphere/sdk/products/attributes/RichReferenceAttributeType.java
- commercetools-models/src/test/java/io/sphere/sdk/customers/commands/CustomerUpdateCommandIntegrationTest.java
- commercetools-models/src/test/java/io/sphere/sdk/producttypes/ProductTypeAttributesIntegrationTest.java
- commercetools-test-lib/src/main/java/io/sphere/sdk/test/SphereTestUtils.java
> reference attribute types are equal if referenceTypeId is equal
