commercetools/commercetools-jvm-sdk

sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
sphere-test-lib/src/main/java/io/sphere/sdk/test/RetryIntegrationTest.java

So the problem is that there is a delay from the moment the products are in ES and the moment when they can be used for some facets, sort and filter requests. I solved it with an additional check that seems to work very well in localhost. Anyway, I've increased the delay just to make sure the check is not skipping some case.
Please @schleichardt review.
Fixes https://github.com/sphereio/sphere-jvm-sdk/issues/382

Add additional check to avoid flaky tests.

---

sphere-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
sphere-java-client-ning-1_8/src/main/java/io/sphere/sdk/client/SphereClientFactory.java
sphere-java-client-ning-1_9/src/main/java/io/sphere/sdk/client/SphereClientFactory.java
sphere-models/src/it/java/io/sphere/sdk/customers/commands/CustomerSignInCommandTest.java
sphere-models/src/main/java/io/sphere/sdk/customers/commands/CustomerSignInCommand.java

The CustomerSignInCommand throwed in the error case an exception without the request and the response information.
I refactored a little bit the client impl to make the stack trace nicer.

Improve error messages and documentation for CustomerSignInCommand. #397

---

README.md
project/Libs.scala

@nkuehn @hajoeichler @lauraluiz 
To say it in other words: If everything works fine I will update the production code dependencies next time for the next major release (2.0.0). So that will maybe in half a year or next year.
I would like to keep the current dependencies for stability reasons. I won't update it to be up to date and put migration problems on the users.
If ning Async HTTP Client 2.0.0 will be released, I just create a new module sdk http client module which can be pulled.

Update dependencies. close #612

---

sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchFilterTypesIntegrationTest.java
sphere-models/src/it/java/io/sphere/sdk/products/ProductProjectionSearchIntegrationTest.java
sphere-test-lib/src/main/java/io/sphere/sdk/test/RetryIntegrationTest.java

@schleichardt please review. It is just an improvement of the retry method, which now increases the delay quadratically until it reaches the maximum retry interval specified. This way we might save some time when it fails due to unsynchronized resources.
I then allowed up to 10 seconds of retry. I may lower this if I see it is not necessary, but actually if it is really unnecessary it should never have to wait that much :)

Retry quadratically

---

sphere-common/src/main/java/io/sphere/sdk/utils/SphereInternalLogger.java

Currently we are getting defined loggers such as:
```
sphere.customer-groups?where=name%3D%22b2c%22.responses.queries
```
With this fix we would get instead:
```
sphere.customer-groups.responses.queries
```

Split URL before query string, closes #802

---

sphere-common/src/main/java/io/sphere/sdk/queries/DirectionlessQuerySort.java
sphere-common/src/main/java/io/sphere/sdk/queries/IntegerLikeQuerySortingModel.java
sphere-common/src/main/java/io/sphere/sdk/queries/IntegerQuerySortingModel.java
sphere-common/src/main/java/io/sphere/sdk/queries/LongQuerySortingModel.java
sphere-common/src/main/java/io/sphere/sdk/queries/QuerySortingModel.java
sphere-common/src/main/java/io/sphere/sdk/queries/StringQuerySortingModel.java
sphere-common/src/main/java/io/sphere/sdk/queries/StringQuerySortingModelImpl.java
sphere-common/src/main/java/io/sphere/sdk/queries/TimestampSortingModel.java
sphere-common/src/main/java/io/sphere/sdk/queries/TimestampSortingModelImpl.java
sphere-common/src/test/java/io/sphere/sdk/queries/StringQuerySortingModelTest.java
sphere-models/src/it/java/io/sphere/sdk/categories/queries/CategoryQueryTest.java
sphere-models/src/it/java/io/sphere/sdk/customobjects/queries/CustomObjectQueryTest.java
sphere-models/src/it/java/io/sphere/sdk/inventory/queries/InventoryEntryQueryTest.java
sphere-models/src/it/java/io/sphere/sdk/products/queries/ProductProjectionQueryTest.java
sphere-models/src/it/java/io/sphere/sdk/shippingmethods/queries/ShippingMethodQueryModelTest.java
sphere-models/src/test/java/io/sphere/sdk/orders/queries/SyncInfoQueryModelTest.java
src/test/java/io/sphere/sdk/meta/QueryDocumentationTest.java
src/test/java/io/sphere/sdk/queries/QueryDemo.java

@lauraluiz please review.
With this PR I want to make it more fluent to create sort expressions by removing the need to lookup the constants or make imports. Maybe we should rename DirectionlessQuerySort.

Change query sort DSL. close #764

---

project/Build.scala
project/Libs.scala
sdk-http-ahc-1_8/src/main/java/io/sphere/sdk/http/AsyncHttpClientAdapterImpl.java
sdk-http-ahc-1_9/src/main/java/io/sphere/sdk/http/DefaultAsyncHttpClientAdapterImpl.java
sdk-http/src/main/java/io/sphere/sdk/http/HttpHeaders.java
sphere-java-client-ahc-1_8/src/it/java/io/sphere/sdk/client/AsyncHttpClientAdapter18Test.java
sphere-java-client-ahc-1_9/src/it/java/io/sphere/sdk/client/AsyncHttpClientAdapter19Test.java
sphere-java-client-apache-async/src/it/java/io/sphere/sdk/client/ApacheHttpClientAdapterTest.java
sphere-java-client-internal-test/src/main/java/io/sphere/sdk/client/HttpClientAdapterTest.java

@panshul007 Can you please try out a snapshot if it works for you? The version number is "1.0.0-M20-issue-799-SNAPSHOT"
You may need to add the sonatype snapshots resolver:
```
resolvers ++= Seq (
Resolver.sonatypeRepo("releases"),
Resolver.sonatypeRepo("snapshots"),
Resolver.bintrayRepo("commercetools", "maven")
)
```

Fix missing Content-Length in AHC. close #799

---

sphere-models/src/it/java/io/sphere/sdk/products/ProductCategoryOrderHintTest.java
sphere-models/src/main/java/io/sphere/sdk/products/search/CategoryOrderHintsSortSearchModel.java
sphere-models/src/main/java/io/sphere/sdk/products/search/ProductDataSortSearchModel.java
sphere-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionSortSearchModel.java

In ProductCategoryOrderHintTest was already a good place for the meta model usage.

Put Category Order Hints to sort search model. close #794

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-internal-docs/src/test/java/io/sphere/sdk/meta/M26Demo.java
commercetools-models/src/main/java/io/sphere/sdk/products/attributes/AttributeExtraction.java
commercetools-models/src/main/java/io/sphere/sdk/products/attributes/DefaultProductAttributeFormatter.java
commercetools-models/src/main/java/io/sphere/sdk/products/attributes/LocalizedToStringProductAttributeConverter.java
commercetools-models/src/test/java/io/sphere/sdk/products/attributes/DefaultProductAttributeFormatterIntegrationTest.java

release notes:
```html
<li class=change-in-release>rename {@code LocalizedToStringProductAttributeConverter} 
to {@link io.sphere.sdk.products.attributes.DefaultProductAttributeFormatter}</li>
<li class=new-in-release>make constructors of 
{@link io.sphere.sdk.products.attributes.DefaultProductAttributeFormatter} public</li>
<li class=new-in-release>add alias
{@link io.sphere.sdk.products.attributes.DefaultProductAttributeFormatter#format(Attribute, Referenceable)}
for
{@link io.sphere.sdk.products.attributes.DefaultProductAttributeFormatter#convert(Attribute, Referenceable)}</li>
```

rename and open LocalizedToStringProductAttributeConverter, close #992

---

commercetools-convenience/src/main/java/io/sphere/sdk/client/metrics/MetricSphereRequest.java
commercetools-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedDeserializationDuration.java
commercetools-convenience/src/main/java/io/sphere/sdk/client/metrics/ObservedTotalDuration.java
commercetools-convenience/src/main/java/io/sphere/sdk/client/metrics/SimpleMetricsSphereClient.java
commercetools-convenience/src/test/java/io/sphere/sdk/client/metrics/SimpleMetricsSphereClientTest.java

@lauraluiz  please review
release notes:
```html
<li class=new-in-release>{@link ObservedTotalDuration#getErrorResult()},
{@link ObservedTotalDuration#getSuccessResult()},
{@link ObservedDeserializationDuration#getHttpResponse()}
and {@link ObservedDeserializationDuration#getResult()} 
for better analysis of metrics with the
{@link io.sphere.sdk.client.metrics.SimpleMetricsSphereClient}</li>
```

metrics improvements, close #995

---

commercetools-java-client-core/src/main/java/io/sphere/sdk/client/BlockingSphereClient.java
commercetools-java-client-core/src/main/java/io/sphere/sdk/client/BlockingSphereClientImpl.java
commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TimeoutSphereClientDecorator.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientUtils.java

release notes:
```html
<li class=fixed-in-release>conversion from {@link Duration} into {@link TimeUnit} for
{@link io.sphere.sdk.client.BlockingSphereClient#executeBlocking(SphereRequest, Duration)},
{@link io.sphere.sdk.client.TimeoutSphereClientDecorator#of(SphereClient, Duration)} 
and the methods of {@link io.sphere.sdk.client.SphereClientUtils} (was causing silly timeouts)
</li>
```

fix bug wrong conversion Duration to TimeUnit

---

commercetools-java-client-core/src/main/java/io/sphere/sdk/client/ExceptionFactory.java
commercetools-java-client-core/src/main/java/io/sphere/sdk/client/SphereClientImpl.java
commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TestDoubleSphereClientFactory.java
commercetools-models/src/main/java/io/sphere/sdk/products/Product.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductLike.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductProjection.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductProjectionImpl.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductToProductProjectionWrapper.java
commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductDataFilterSearchModel.java
commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionFilterSearchModel.java
commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantFilterSearchModel.java
commercetools-models/src/test/java/io/sphere/sdk/products/ProductFixtures.java
commercetools-models/src/test/java/io/sphere/sdk/products/search/ExistFilterIntegrationTest.java
commercetools-models/src/test/java/io/sphere/sdk/products/search/ExistsAndMissingFilterIntegrationTest.java
commercetools-models/src/test/java/io/sphere/sdk/products/search/ProductProjectionSearchTest.java
commercetools-models/src/test/java/io/sphere/sdk/producttypes/ProductTypeFixtures.java
commercetools-models/src/test/java/io/sphere/sdk/states/StateFixtures.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/EnumFilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/ExistsAndMissingFilterSearchModelSupport.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/ExistsAndMissingFilterSearchModelSupportImpl.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/ExistsAndMissingFilterSearchModelSupportUtils.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/ExistsFilterSearchModelSupport.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/LocalizedEnumFilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/LocalizedStringFilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/MissingFilterSearchModelSupport.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/MoneyFilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/ReferenceFilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/SearchModelImpl.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFilterBaseSearchModel.java

- add missing filter which excludes elements which have no value for a certain field
- add exists filter which only includes elements which have no value for a certain field
- improve error reporting, now the http request is also shown if a search request and others fail
- it also contains a filter for taxCategory and sku
- add state field to product projection

exists & missing filter, close #1027, close #1052, close #1058

---

commercetools-models/src/test/java/io/sphere/sdk/payments/commands/PaymentUpdateCommandIntegrationTest.java

@schleichardt one more review please.
Now all tests are almost always green locally.

messages are created asynchronously

---

commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddExternalImage.java
commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/AddPrice.java
commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/RemoveImage.java
commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/RemoveVariant.java
commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetAttribute.java
commercetools-models/src/main/java/io/sphere/sdk/products/commands/updateactions/SetPrices.java
commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java

@yanns @ccsalazarr-commercetools please review
I changed some signatures to reduce confusion. So if the name of the method starts with `ofSku` then the first parameter should be the SKU, especially `public static RemoveImage ofSku(final String imageUrl, final String sku)` was counterintuitive.
In the docu I also removed the classic `of` method links since it is better to use only the named `of` methods like `ofSku`.

Product updates via sku improvements

---

.travis.yml
commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductAttributeFilterSearchModel.java
commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductProjectionFilterSearchModel.java
commercetools-models/src/main/java/io/sphere/sdk/products/search/ProductVariantFilterSearchModel.java
commercetools-models/src/test/java/io/sphere/sdk/products/search/ExistsAndMissingFilterIntegrationTest.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/FilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/LocalizedStringFilterSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFilterBaseSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFilterExistsAndMissingSearchModel.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermFilterSearchModelImpl.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/search/model/TermModelImpl.java

This PR fixes the type hierarchy for the `exists` and `missing` predicates we discussed.

Refactor exists and missing filter

---

commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java

Just a little convenience change for when you store the "integrationtest.properties" in a different location then the usual ones.

Review corrections

---

commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraftBuilder.java
commercetools-models/src/test/java/io/sphere/sdk/carts/commands/CartUpdateCommandIntegrationTest.java

simple PR to solve #1559 :
just add `@Nullable` annotation to `ProductDraft` and `ProductDraftBuilder` since it is supported by platform documenation

#1559: mark masterVariant in ProductDraft and ProductDraftBuilder

---

.travis.yml

by the help of the `&&` directive the commands are executed in chain, and fail once the first command in chain fails. this allows us to avoid also the overhead induced by travis stages.

Evaluate travis build stages

---

commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java

SSL is not at all activated due to the fact that CI uses only HTTP, but when possible HTTPS should be reactivated.

SSL should be activated in tests when possible

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-models/src/main/java/io/sphere/sdk/subscriptions/MessageSubscriptionPayload.java
commercetools-models/src/main/java/io/sphere/sdk/subscriptions/MessageSubscriptionPayloadImpl.java
pom.xml

Updating jackson version,
You might notice that i removed the constructor in `MessageSubscriptionPayloadImpl`, actually this is due to the fact that in the new jackson library you can't use `@JsonUnwrapped` combined with constructor.
closes #1601

Updating jackson version

---

commercetools-models/src/main/java/io/sphere/sdk/channels/ChannelDraft.java
commercetools-models/src/test/java/io/sphere/sdk/channels/ChannelDraftBuilderTest.java

This PR addresses #1775:
1. Make `ChannelDraft` extend `CustomDraft`. b8fa8e3 | Unit tests were added here: 
5f1f483
2. Boy-scout-change: Remove redundant `getKey()` and `getCustom()` in `ChannelDraft` interface which will be inherited from the super interfaces `WithKey` and `CustomDraft` anyway.
Closes #1775

Make ChannelDraft extend CustomDraft

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-java-client-core/src/main/java/io/sphere/sdk/client/ExceptionFactory.java
commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java
commercetools-models/src/test/java/io/sphere/sdk/client/ApacheClientIntegrationTest.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/InvalidClientCredentialsException.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/InvalidScopeException.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/InvalidTokenException.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/UnauthorizedException.java
commercetools-test-lib/src/main/java/io/sphere/sdk/test/IntegrationTest.java

When using an invalid project key, the client does not shutdown which leads to multiple useless retries, tis should be fixed via client shutdown, which prevent further requests.
related to #1817
Closes #1817

invalid project key should lead to client shutdown

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/json/ZonedDateTimeSerializer.java
commercetools-sdk-base/src/test/java/io/sphere/sdk/json/SphereJsonUtilsTest.java

Now the ZonedDateTime formatter should always include milliseconds

Change date time formatter

---

commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscount.java
commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraft.java
commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftBuilder.java
commercetools-models/src/main/java/io/sphere/sdk/cartdiscounts/CartDiscountDraftDsl.java

We are using a generic utility for calculating custom type update actions, but we are relying on Custom interface on our generic method, so it would be nice to add the Custom interface to CartDiscount and CartDiscountDraft like Category.
[Here](https://github.com/commercetools/commercetools-sync-java/blob/986b6250110654abac2fd68d3f91833c4d4d45ab/src/main/java/com/commercetools/sync/commons/utils/CustomUpdateActionUtils.java#L38-L62
) you can check our use case:
Closes #1918

#1918 extend from Custom interfaces for CartDiscount(Draft)

---

.travis.yml
commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-models/src/main/java/io/sphere/sdk/categories/Category.java
commercetools-models/src/main/java/io/sphere/sdk/categories/CategoryDraft.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductDraft.java
commercetools-models/src/main/java/io/sphere/sdk/products/ProductLike.java
commercetools-models/src/test/java/io/sphere/sdk/categories/CategoryDraftTest.java
commercetools-models/src/test/java/io/sphere/sdk/categories/CategoryTest.java
commercetools-models/src/test/java/io/sphere/sdk/products/ProductDraftTest.java
commercetools-models/src/test/java/io/sphere/sdk/products/ProductLikeTest.java

- Extends WithKey interface in Category, CategoryDraft, ProductLike and ProductDraft.
Closes #1957

1957 Extend WithKey interface in Category, CategoryDraft, ProductLike and ProductDraft.

---

commercetools-models/src/main/java/io/sphere/sdk/types/customupdateactions/SetCustomFieldBase.java

According to the commercetools platform, API users can set [] as a value for PriceCustomField. But when we use the jvm-sdk, this has been restricted. From jvm-sdk the value is being ignore which leads the platform to remove the attribute. This behaviour is inconsistent compared to commercetools platform, in fact it causes failures for commercetools-sync-java library.
Example scenario:
```
"prices": [
{
"value": {
"type": "centPrecision",
"currencyCode": "EUR",
"centAmount": 4200,
"fractionDigits": 2
},
"id": "561f7353-1889-4ab3-bf6d-66531745d400",
"custom": {
"type": {
"typeId": "type",
"id": "00f62841-7974-4ce5-8727-dc9703596c90"
},
"fields": {
"touchpoints": ["some url"],
"today": "2010-02-02"
}
}
}
]
```
In above situation, if commercetools-sync-java tries to set value as [] for …

allow empty array values for customfields

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-models/src/main/java/io/sphere/sdk/types/customupdateactions/SetCustomFieldBase.java
commercetools-models/src/test/java/io/sphere/sdk/products/commands/ProductUpdateCommandIntegrationTest.java

Test for allowing empty values for customField attributes. 
Refer to this PR -> https://github.com/commercetools/commercetools-jvm-sdk/pull/1963
Closes #

test for allow empty array values for customfields

---

commercetools-models/src/test/java/io/sphere/sdk/products/queries/ProductProjectionQueryIntegrationTest.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/MetaModelQueryDsl.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/queries/MetaModelQueryDslImpl.java

The API supports the creation of parametrized queries. This starts by just adding the possibility to add them using string predicates.
It should be discussed how this could be improved for example to have also support in the query predicate builders.

add initial functionality for parametrized queries

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-models/src/main/java/io/sphere/sdk/orders/ParcelDraft.java

Added new ParcelDraft 'of' method that accepts a list of DeliveryItems.

---

commercetools-convenience/src/main/java/io/sphere/sdk/client/correlationid/CorrelationIdRequestDecorator.java
commercetools-convenience/src/test/java/io/sphere/sdk/client/correlationid/CorrelationIdRequestDecoratorTest.java
commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java

Often times different services using the JVM SDK need to attach their own correlation id to the requests header going to CTP, treating CTP as an upstream service to this service written using the JVM SDK. 
I thought instead of implementing this decorator class on every service/project that needs it. It would make sense to have it written once and reuse it so (I had this lib https://github.com/heshamMassoud/commercetools-correlation-id-decorator) but then I thought It would make sense to have it in the convenience module of the SDK itself (along with other decorators provided by the SDK: `QueueSphereClientDecorator`, `RetrySphereClientDecorator`, etc..)

Add correlation id request decorator.

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java
commercetools-models/src/main/java/io/sphere/sdk/messages/GenericMessageImpl.java

Closes #
When: using JsonDeserialize method on Message.class object to convert it into a LineItemStateTransitionMessage.class, e.g. message.as(LineItemStateTransitionMessage.class)
Then: There is null value in the "type" and "resourceUserProvidedIdentifiers" fields

fixed generic message deserialization

---

commercetools-models/src/test/java/io/sphere/sdk/carts/ExternalPricesIntegrationTest.java
commercetools-models/src/test/java/io/sphere/sdk/products/ProductFixtures.java

Looks like 2 tests were using unpublished products, which our backend doesn't accept anymore. These changes are already deployed to production and since our tests are green, they should also work on staging too.
Closes #2013

Fix tests using unpublished products

---

pom.xml

Closes #2063 
The updated moneta version includes a fix where initialization of the currency provider can fail when done concurrently.

bump moneta version

---

commercetools-internal-docs/src/main/java/io/sphere/sdk/meta/ReleaseNotes.java

Accidentally committed the anonymousId support for shopping lists directly to master. This adds the missing release note

add missing release note

---

commercetools-java-client-core/src/main/java/io/sphere/sdk/client/TokensSupplierImpl.java
commercetools-models/src/test/java/io/sphere/sdk/client/ApacheClientIntegrationTest.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfig.java
commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereClientConfigUtils.java

refactor tokensupplier to use client default scopes if none are given
